// PenApp's strings in English, Spanish and Portuguese. Kept beside the component rather than
// inline because PenApp is long enough already; every other component holds its own.

import type { Copy } from '@/lib/pen/i18n'
import type { PenStatus } from '@/lib/pen/store'

const en = {
  // errors and progress
  deleteFailed: 'Could not delete that recording.',
  notesFailed: 'Could not write the notes.',
  noRecordingsIn: (dir: string) => `No recordings in “${dir}”. Recorders often keep files in a subfolder — try picking that one.`,
  notMedia: 'Those files aren’t audio or video that can be read here.',
  consentFirst: 'Confirm consent first. Florida requires every party to agree to being recorded.',
  phasePreparing: 'Preparing audio',
  phaseSlot: 'Getting an upload slot',
  phaseUploading: (note: string) => `Uploading · ${note}`,
  phasePiece: (i: number, n: number, size: string) => `Uploading part ${i} of ${n} · ${size}, as it is`,
  phaseSaving: 'Saving',
  phaseSending: 'Sending for transcription',
  uploadUrlFailed: 'Could not get an upload URL.',
  tooBigCompressed: (mb: string) =>
    `${mb} even after compressing — that's several hours of audio. Split it into shorter files and upload them separately; they'll be joined back up.`,
  tooBigNoCompress: (mb: string) =>
    `${mb} is over the 50 MB per-file limit, and this browser can't compress audio. Try again in Chrome, which can.`,
  saveRecordingFailed: 'Could not save the recording.',
  transcribeFailed: 'Transcription failed to start.',
  saveFailed: (status: number) => `Save failed (${status}).`,
  untitled: 'Untitled',
  recordings: ['recording', 'recordings'] as [string, string],

  // sidebar
  brandTag: 'Capture. Understand. Do.',
  connectPen: 'Connect pen',
  addFiles: 'Add audio files',
  orDrag: 'or drag them here',
  importTranscript: 'Import a transcript',
  mUploadTitle: 'Add a recording',
  mUploadLede: 'From your phone, the pen or WhatsApp. Notes arrive in a few minutes.',
  mChoose: 'Choose audio files',
  mChooseSub: 'Voice memos, the pen’s files, any recording',
  mHistory: 'History',
  mAll: 'All',
  mRecordingTitle: 'Recording',
  iosPenTitle: 'Uploading from the pen? Read this first',
  iosPenLede: 'iPhone can’t upload straight from the pen. Copy the recording to your iPhone first, then upload it:',
  iosPenSteps: ['Open the Files app and tap JUNO (the pen), then RECORD.', 'Press and hold the recording, then tap Copy.', 'Go back to On My iPhone, press and hold an empty space, then tap Paste.', 'Come back here, tap Choose audio files, then Choose Files → On My iPhone.'],
  iosPenTip: 'On a computer you can upload straight from the pen.',
  pausedTitle: (d: string) => `Paused until ${d}`,
  pausedSub: 'Your recordings stay open. Resume to add new ones.',
  resumeNow: 'Resume now',
  inviteFriends: 'Invite friends, get free months',
  help: 'Help',
  promoEyebrow: 'New: refer a colleague',
  promoTitle: 'Give a month, get a month',
  promoLede: 'Share your link with a colleague. Their first month is free, and you get a free month for every friend who pays.',
  promoTiers: [['1 friend', '1 free month'], ['3 friends', '4 free months'], ['10 friends', 'a free year']] as [string, string][],
  promoGo: 'Get my invite link',
  promoLater: 'Not now',
  upWaiting: 'Waiting',
  upTitle: (done: number, total: number) => `Uploading · ${done} of ${total} done`,
  upKeepOpen: 'Keep using Juno as normal. Leave this tab open until it finishes.',
  upKeepOpenPhone: 'Keep Juno open on screen until it finishes.',
  upDoneTitle: (n: number) => (n === 1 ? 'Recording uploaded' : `${n} recordings uploaded`),
  upDoneBody: 'We’ll email you each summary as soon as it’s ready, usually within a few minutes.',
  upHeld: (n: number) => (n === 1 ? '1 is waiting for recording hours.' : `${n} are waiting for recording hours.`),
  upFailed: (n: number) => (n === 1 ? '1 didn’t upload:' : `${n} didn’t upload:`),
  upShow: 'Show files',
  upHide: 'Hide files',
  upClose: 'Close',
  upAskWa: 'Ask about them on WhatsApp',
  upConnectWa: 'Connect WhatsApp to ask about them',
  waCallTitle: 'Ask Juno on WhatsApp',
  waCallBody: 'Text a question about any meeting and get the answer in seconds. Tap one to try it.',
  waCallExamples: ['What did I promise to send them?', 'What were the next steps from my last meeting?', 'What did they say about the price?'] as string[],
  waCallConnect: 'Connect WhatsApp',
  waCallConnectBody: 'Link your phone once, then text Juno a question about any meeting and get the answer in seconds.',
  waCallHide: 'Hide',
  fbEyebrow: 'Two minutes, three questions',
  fbTitle: 'Help us make Juno better',
  fbQ1: 'How would you feel if you could no longer use Juno Pen?',
  fbOpts: { very: 'Very disappointed', somewhat: 'Somewhat disappointed', not: 'Not disappointed' } as Record<'very' | 'somewhat' | 'not', string>,
  fbQ2: 'What’s the one thing we should fix or add?',
  fbQ3: 'Who would you tell about Juno, and what would you say it’s for?',
  fbQ3Ph: 'e.g. “Any agent who does showings: it writes the follow-ups for you.”',
  fbOptional: 'optional',
  fbSend: 'Send',
  fbSending: 'Sending…',
  fbThanksTitle: 'Thank you',
  fbThanks: 'We read every answer. If you wrote something we can act on, you’ll hear from us.',
  fbDone: 'Back to Juno',
  notionSend: 'Send to Notion',
  importNotion: 'Import from Notion',
  notionSending: 'Sending…',
  notionOpen: 'Open in Notion',
  readOnlyTitle: 'Your account is read-only',
  readOnlySub: 'Your plan has ended. Everything you recorded stays open to read; reactivate to add recordings, search and chat.',
  reactivate: 'Reactivate',
  pillTrial: (n: number) => (n === 1 ? 'Trial: 1 day left' : `Trial: ${n} days left`),
  pillEnding: (n: number) => (n === 1 ? 'Plan ends in 1 day' : `Plan ends in ${n} days`),
  pillReadOnly: 'Read-only',
  resuming: 'Resuming…',
  openWhatsApp: 'Open WhatsApp',
  useWhatsApp: 'Use WhatsApp',
  waLinkedSub: 'Send recordings, ask questions',
  waUnlinkedSub: 'Send recordings from your phone',
  home: 'Home',
  allRecordings: 'All recordings',
  /** The sidebar's narrower slot. */
  allRecordingsNav: 'All recordings',
  quote: ['Small moments.', 'Bigger progress.'] as [string, string],
  chats: 'Chats',
  newChat: 'New chat',
  chatsEmpty: 'Ask something in the search bar and it lands here.',
  untitledChat: 'Untitled chat',
  pages: 'Pages',

  // header and banners
  browseAria: 'Browse recordings and categories',
  browse: 'Browse',
  waPhoneLinked: 'Send a recording on WhatsApp',
  waPhoneUnlinked: 'Use Juno Pen on WhatsApp',
  waPhoneLinkedSub: 'Plug the pen in, then share the file to the chat',
  waPhoneUnlinkedSub: 'Send recordings and ask questions from your phone',
  loadError: (e: string) => `Couldn’t load recordings: ${e}`,
  heldNotice: "You've passed this month's fair-use limit. Your upload is saved and will be transcribed when the month resets. Reply to any Juno Pen email if you need more.",
  noPicker: 'This browser can’t read a folder directly. Use Chrome or Edge for one-click “Connect pen”, or drag files in below.',
  runTitle: (n: number, dur: string) => `${n} recordings look like one ${dur} meeting.`,
  runBody: 'The pen stops at 60 minutes and starts a new file.',
  untitledLower: 'untitled',
  joining: 'Joining…',
  join: 'Join into one meeting',
  close: 'Close',
  closeNav: 'Close navigation',
  chooseRecording: 'Choose a recording on the left.',
  askPerson: (label: string) => `Show me all the conversations with @${label}`,

  // rail
  recent: 'Recent recordings',
  new: 'New',
  emptyCat: 'Nothing in this category.',
  showEverything: 'Show everything',
  emptyAll: ['Nothing yet. Plug the pen into USB, press ', ', and choose the drive that appears.'] as [string, string],
  status: {
    uploaded: 'uploaded',
    held: 'needs hours',
    transcribing: 'transcribing',
    transcribed: 'transcribed',
    noting: 'noting',
    noted: 'noted',
    error: 'error',
  } as Record<PenStatus, string>,
  parts: (n: number) => `${n} parts`,

  // account menu
  settings: 'Settings',
  tour: 'Take the tour',
  customers: 'Customers',

  // search
  suggOpen: (n: number) => `What have I still not done? (${n} open)`,
  suggClient: (c: string) => `What does ${c} actually want?`,
  suggCategory: (c: string) => `Sum up my ${c} recordings`,
  suggOwes: 'Who owes me something?',
  suggFallback: ['What did I miss this week?', 'What was left unresolved?', 'What did I commit to?'],
  searchPlaceholder: 'Ask anything… type @ for a person or recording',
  searchAria: 'Ask your archive',
  tryAsking: 'Try asking',

  // title and category
  clickRename: 'Click to rename',
  renameFailed: 'Rename didn’t save — the old name is back.',
  working: 'Working…',
  setCategory: 'Set a category',
  typeOwn: 'Type your own…',

  // import tray
  addRecording: 'Add a recording',
  doneTitle: 'We’ll email you when it’s ready.',
  doneBody: 'Transcribing and writing up takes a few minutes. You can close this — the briefing lands in your inbox on its own.',
  keepOpen: 'Keep this tab open until it finishes — leaving Safari stops the upload.',
  remove: (name: string) => `Remove ${name}`,
  consentPhone: 'Everyone recorded agreed to it, and this contains no patient or medical information.',
  consentDesk: 'Everyone recorded agreed to it, and this recording contains no patient or medical information.',
  addN: (n: number) => (n > 1 ? `Add ${n} recordings` : 'Add recording'),
  nameLater: 'You can name who it was with afterwards.',
  done: 'Done',
  onPen: (n: number, pen: string) => `${n} on “${pen}”`,
  readyImport: 'Ready to import',
  clear: 'clear',
  whoOnCall: 'Who was on this call (optional)',
  whoHint: 'Leave it empty and the notes will suggest who they heard.',
  importN: (n: number) => (n ? `Import ${n} and transcribe` : 'Import and transcribe'),

  // detail
  noPartTranscript: 'This part has no transcript yet.',
  speakers: ['speaker', 'speakers'] as [string, string],
  aiSummarised: 'AI summarised',
  imported: 'Imported',
  transcribed: 'Transcribed',
  chipTranscribing: 'Transcribing',
  chipNoting: 'Writing notes',
  chipError: 'Something failed',
  chipHeld: 'Waiting for hours',
  joinedNote: (n: number) => `The pen hit its 60-minute file limit, so this meeting arrived in ${n} pieces. They are read as one — both recordings are still here.`,
  separating: 'Separating…',
  separate: 'Separate them again',
  redoNotes: 'Redo notes',
  writeNotes: 'Write the notes',
  hideChat: 'Hide chat',
  askMeeting: 'Ask this meeting',
  deleteForGood: 'Delete for good?',
  keep: 'Keep',
  delete: 'Delete',
  deleteTitle: 'Delete this recording and its audio',
  tabs: { note: 'note', transcript: 'transcript' },
  category: 'Category',
  notSure: 'not sure what this was',
  or: ' or ',
  noTranscript: 'No transcript yet.',
  partSeam: (n: number, at: string) => `Part ${n} · new file at ${at}`,
  partNote: 'Speakers are labelled fresh in each file, so “Speaker A” here may be someone else than “Speaker A” above. The notes above already account for that.',
  mTranscribing: 'Transcribing. This runs on its own — you can close the tab.',
  mUploaded: 'Uploaded, waiting to be sent for transcription.',
  mHeld: "Saved, and waiting: this month's fair-use limit is used up. It will be transcribed automatically when the month resets.",
  mNotesFailed: 'The transcript came through but the notes failed. Press “Write the notes” to try again.',
  more: 'More',
  moreActions: 'More actions',
  relabeled: (t: string) => `Category changed to “${t}”. Rewrite the notes for it? Your current notes stay unless you do.`,
  redoAsType: 'Rewrite the notes',
  keepNotes: 'Keep these notes',
  mEmpty: 'No one spoke on this recording (a pen left recording in a pocket, perhaps), so there are no notes. You can delete it.',
  mReady: 'The transcript is ready and the notes are being written. They appear here in a minute or two, and we’ll email you.',
  aiSummary: 'AI meeting summary',
  byAi: 'Generated by AI',
  stillOpen: 'Still open',
  decided: 'Decided',
  nextActions: 'Next actions',
  nDone: (d: number, n: number) => `${d}/${n} done`,
  priority: 'PRIORITY',
  missed: 'You might have missed',

  // showing
  roomByRoom: 'Room by room',
  objections: 'Objections',
  signals: 'Buying signals',
  wantTitle: 'What they actually want',
  wantNote: 'Inferred from what they reacted to, not from what they said.',
  sentiment: { loved: 'loved', liked: 'liked', neutral: 'neutral', disliked: 'disliked' } as Record<string, string>,
  strength: { strong: 'strong', medium: 'medium', weak: 'weak' } as Record<string, string>,

  // meeting chat
  chatViewing: ['What did they actually like?', 'What were the objections?', 'Did they say they’d come back?'],
  chatClinic: ['What needs doing today?', 'Who owes me something?', 'What did I agree to follow up on?'],
  chatDefault: ['What did I commit to?', 'What did I miss?', 'Was anything left unresolved?'],
  noAnswer: 'Could not get an answer.',
  chatIntro: 'Answers come only from this recording. If it isn’t in there, it’ll say so rather than guess.',
  chatPlaceholder: 'Ask about this meeting…',
  ask: 'Ask',
}

export type AppCopy = typeof en

const es: AppCopy = {
  deleteFailed: 'No se pudo borrar esa grabación.',
  notesFailed: 'No se pudieron escribir las notas.',
  noRecordingsIn: (dir) => `No hay grabaciones en “${dir}”. Las grabadoras suelen guardarlas en una subcarpeta: prueba eligiendo esa.`,
  notMedia: 'Esos archivos no son audio ni video que se pueda leer aquí.',
  consentFirst: 'Primero confirma el consentimiento. En Florida, todas las personas grabadas deben estar de acuerdo.',
  phasePreparing: 'Preparando el audio',
  phaseSlot: 'Preparando la subida',
  phaseUploading: (note) => `Subiendo · ${note}`,
  phasePiece: (i, n, size) => `Subiendo parte ${i} de ${n} · ${size}, tal cual`,
  phaseSaving: 'Guardando',
  phaseSending: 'Enviando a transcribir',
  uploadUrlFailed: 'No se pudo preparar la subida.',
  tooBigCompressed: (mb) =>
    `${mb} incluso después de comprimir: son varias horas de audio. Divídelo en archivos más cortos y súbelos por separado; se vuelven a unir solos.`,
  tooBigNoCompress: (mb) =>
    `${mb} supera el límite de 50 MB por archivo, y este navegador no puede comprimir audio. Inténtalo de nuevo en Chrome, que sí puede.`,
  saveRecordingFailed: 'No se pudo guardar la grabación.',
  transcribeFailed: 'No se pudo empezar la transcripción.',
  saveFailed: (status) => `No se pudo guardar (${status}).`,
  untitled: 'Sin título',
  recordings: ['grabación', 'grabaciones'],

  brandTag: 'Graba. Entiende. Actúa.',
  connectPen: 'Conectar el lápiz',
  addFiles: 'Agregar audios',
  orDrag: 'o arrástralos aquí',
  importTranscript: 'Importar una transcripción',
  mUploadTitle: 'Agrega una grabación',
  mUploadLede: 'Desde tu celular, el lápiz o WhatsApp. Las notas llegan en unos minutos.',
  mChoose: 'Elegir audios',
  mChooseSub: 'Notas de voz, archivos del lápiz, cualquier grabación',
  mHistory: 'Historial',
  mAll: 'Todas',
  mRecordingTitle: 'Grabación',
  iosPenTitle: '¿Subes desde el lápiz? Lee esto primero',
  iosPenLede: 'El iPhone no puede subir directo desde el lápiz. Copia la grabación a tu iPhone y luego súbela:',
  iosPenSteps: ['Abre la app Archivos y toca JUNO (el lápiz), luego RECORD.', 'Mantén presionada la grabación y toca Copiar.', 'Vuelve a En mi iPhone, mantén presionado un espacio vacío y toca Pegar.', 'Vuelve aquí, toca Elegir audios y luego Elegir archivos → En mi iPhone.'],
  iosPenTip: 'En un computador puedes subir directo desde el lápiz.',
  pausedTitle: (d) => `En pausa hasta el ${d}`,
  pausedSub: 'Tus grabaciones siguen disponibles. Reactiva tu plan para agregar nuevas.',
  resumeNow: 'Reactivar ahora',
  inviteFriends: 'Invita amigos y gana meses gratis',
  help: 'Ayuda',
  promoEyebrow: 'Nuevo: recomienda a un colega',
  promoTitle: 'Regala un mes, gana un mes',
  promoLede: 'Comparte tu enlace con un colega. Su primer mes es gratis, y tú ganas un mes gratis por cada amigo que pague.',
  promoTiers: [['1 amigo', '1 mes gratis'], ['3 amigos', '4 meses gratis'], ['10 amigos', 'un año gratis']],
  promoGo: 'Ver mi enlace de invitación',
  promoLater: 'Ahora no',
  upWaiting: 'En espera',
  upTitle: (done, total) => `Subiendo · ${done} de ${total} listas`,
  upKeepOpen: 'Sigue usando Juno con normalidad. Deja esta pestaña abierta hasta que termine.',
  upKeepOpenPhone: 'Mantén Juno abierto en pantalla hasta que termine.',
  upDoneTitle: (n) => (n === 1 ? 'Grabación subida' : `${n} grabaciones subidas`),
  upDoneBody: 'Te enviaremos cada resumen por correo apenas esté listo, normalmente en pocos minutos.',
  upHeld: (n) => (n === 1 ? '1 espera horas de grabación.' : `${n} esperan horas de grabación.`),
  upFailed: (n) => (n === 1 ? '1 no se pudo subir:' : `${n} no se pudieron subir:`),
  upShow: 'Ver archivos',
  upHide: 'Ocultar archivos',
  upClose: 'Cerrar',
  upAskWa: 'Pregunta sobre ellas por WhatsApp',
  upConnectWa: 'Conecta WhatsApp para preguntar sobre ellas',
  waCallTitle: 'Pregúntale a Juno por WhatsApp',
  waCallBody: 'Escribe una pregunta sobre cualquier reunión y recibe la respuesta en segundos. Toca una para probar.',
  waCallExamples: ['¿Qué prometí enviarles?', '¿Cuáles fueron los próximos pasos de mi última reunión?', '¿Qué dijeron sobre el precio?'],
  waCallConnect: 'Conectar WhatsApp',
  waCallConnectBody: 'Vincula tu teléfono una vez y luego escríbele a Juno una pregunta sobre cualquier reunión.',
  waCallHide: 'Ocultar',
  fbEyebrow: 'Dos minutos, tres preguntas',
  fbTitle: 'Ayúdanos a mejorar Juno',
  fbQ1: '¿Cómo te sentirías si ya no pudieras usar Juno Pen?',
  fbOpts: { very: 'Muy decepcionado/a', somewhat: 'Algo decepcionado/a', not: 'Nada decepcionado/a' },
  fbQ2: '¿Qué es lo único que deberíamos arreglar o agregar?',
  fbQ3: '¿A quién le hablarías de Juno, y para qué le dirías que sirve?',
  fbQ3Ph: 'p. ej. “A cualquier corredor que haga visitas: te escribe los seguimientos.”',
  fbOptional: 'opcional',
  fbSend: 'Enviar',
  fbSending: 'Enviando…',
  fbThanksTitle: 'Gracias',
  fbThanks: 'Leemos todas las respuestas. Si escribiste algo que podamos mejorar, te vamos a contactar.',
  fbDone: 'Volver a Juno',
  notionSend: 'Enviar a Notion',
  importNotion: 'Importar desde Notion',
  notionSending: 'Enviando…',
  notionOpen: 'Abrir en Notion',
  readOnlyTitle: 'Tu cuenta es solo de lectura',
  readOnlySub: 'Tu plan terminó. Todo lo que grabaste sigue disponible para leer; reactívalo para agregar grabaciones, buscar y chatear.',
  reactivate: 'Reactivar',
  pillTrial: (n) => (n === 1 ? 'Prueba: queda 1 día' : `Prueba: quedan ${n} días`),
  pillEnding: (n) => (n === 1 ? 'Tu plan termina en 1 día' : `Tu plan termina en ${n} días`),
  pillReadOnly: 'Solo lectura',
  resuming: 'Reactivando…',
  openWhatsApp: 'Abrir WhatsApp',
  useWhatsApp: 'Usar WhatsApp',
  waLinkedSub: 'Envía grabaciones, haz preguntas',
  waUnlinkedSub: 'Envía grabaciones desde tu celular',
  home: 'Inicio',
  allRecordings: 'Todas las grabaciones',
  allRecordingsNav: 'Grabaciones',
  quote: ['Pequeños momentos.', 'Grandes avances.'],
  chats: 'Chats',
  newChat: 'Nuevo chat',
  chatsEmpty: 'Pregunta algo en la barra de búsqueda y aparecerá aquí.',
  untitledChat: 'Chat sin título',
  pages: 'Páginas',

  browseAria: 'Ver grabaciones y categorías',
  browse: 'Menú',
  waPhoneLinked: 'Envía una grabación por WhatsApp',
  waPhoneUnlinked: 'Usa Juno Pen en WhatsApp',
  waPhoneLinkedSub: 'Conecta el lápiz y comparte el archivo en el chat',
  waPhoneUnlinkedSub: 'Envía grabaciones y haz preguntas desde tu celular',
  loadError: (e) => `No se pudieron cargar las grabaciones: ${e}`,
  heldNotice: 'Pasaste el límite de uso justo de este mes. Tu grabación quedó guardada y se transcribirá cuando empiece el mes. Si necesitas más, responde a cualquier correo de Juno Pen.',
  noPicker: 'Este navegador no puede leer una carpeta directamente. Usa Chrome o Edge para “Conectar el lápiz” con un clic, o arrastra los archivos aquí abajo.',
  runTitle: (n, dur) => `${n} grabaciones parecen una sola reunión de ${dur}.`,
  runBody: 'El lápiz corta a los 60 minutos y empieza un archivo nuevo.',
  untitledLower: 'sin título',
  joining: 'Uniendo…',
  join: 'Unir en una sola reunión',
  close: 'Cerrar',
  closeNav: 'Cerrar el menú',
  chooseRecording: 'Elige una grabación a la izquierda.',
  askPerson: (label) => `Muéstrame todas las conversaciones con @${label}`,

  recent: 'Grabaciones recientes',
  new: 'Nueva',
  emptyCat: 'No hay nada en esta categoría.',
  showEverything: 'Ver todo',
  emptyAll: ['Nada todavía. Conecta el lápiz por USB, presiona ', ' y elige la unidad que aparece.'],
  status: {
    uploaded: 'subida',
    held: 'faltan horas',
    transcribing: 'transcribiendo',
    transcribed: 'transcrita',
    noting: 'escribiendo notas',
    noted: 'lista',
    error: 'error',
  },
  parts: (n) => `${n} partes`,

  settings: 'Ajustes',
  tour: 'Ver el tour',
  customers: 'Clientes',

  suggOpen: (n) => `¿Qué me falta por hacer? (${n} pendientes)`,
  suggClient: (c) => `¿Qué quiere realmente ${c}?`,
  suggCategory: (c) => `Resume mis grabaciones de ${c}`,
  suggOwes: '¿Quién me debe algo?',
  suggFallback: ['¿Qué se me pasó esta semana?', '¿Qué quedó sin resolver?', '¿A qué me comprometí?'],
  searchPlaceholder: 'Pregunta lo que quieras… escribe @ para una persona o grabación',
  searchAria: 'Pregúntale a tu archivo',
  tryAsking: 'Prueba preguntar',

  clickRename: 'Haz clic para cambiar el nombre',
  renameFailed: 'No se guardó el nombre nuevo; volvió el anterior.',
  working: 'Trabajando…',
  setCategory: 'Elegir categoría',
  typeOwn: 'Escribe la tuya…',

  addRecording: 'Agregar una grabación',
  doneTitle: 'Te avisamos por correo cuando esté lista.',
  doneBody: 'Transcribir y escribir las notas toma unos minutos. Puedes cerrar esto: el resumen te llega solo al correo.',
  keepOpen: 'Deja esta pestaña abierta hasta que termine: si sales de Safari, la subida se detiene.',
  remove: (name) => `Quitar ${name}`,
  consentPhone: 'Todas las personas grabadas estuvieron de acuerdo, y no contiene información médica ni de pacientes.',
  consentDesk: 'Todas las personas grabadas estuvieron de acuerdo, y esta grabación no contiene información médica ni de pacientes.',
  addN: (n) => (n > 1 ? `Agregar ${n} grabaciones` : 'Agregar grabación'),
  nameLater: 'Después puedes indicar con quién fue.',
  done: 'Listo',
  onPen: (n, pen) => `${n} en “${pen}”`,
  readyImport: 'Listo para importar',
  clear: 'limpiar',
  whoOnCall: 'Quién estuvo en esta reunión (opcional)',
  whoHint: 'Si lo dejas vacío, las notas sugerirán a quién escucharon.',
  importN: (n) => (n ? `Importar ${n} y transcribir` : 'Importar y transcribir'),

  noPartTranscript: 'Esta parte todavía no tiene transcripción.',
  speakers: ['persona', 'personas'],
  aiSummarised: 'Resumido con IA',
  imported: 'Importada',
  transcribed: 'Transcrita',
  chipTranscribing: 'Transcribiendo',
  chipNoting: 'Escribiendo notas',
  chipError: 'Algo falló',
  chipHeld: 'Esperando horas',
  joinedNote: (n) => `El lápiz llegó a su límite de 60 minutos por archivo, así que esta reunión llegó en ${n} partes. Se leen como una sola; las grabaciones siguen aquí.`,
  separating: 'Separando…',
  separate: 'Separarlas otra vez',
  redoNotes: 'Rehacer notas',
  writeNotes: 'Escribir las notas',
  hideChat: 'Ocultar chat',
  askMeeting: 'Preguntar sobre esta reunión',
  deleteForGood: '¿Borrar para siempre?',
  keep: 'Conservar',
  delete: 'Borrar',
  deleteTitle: 'Borrar esta grabación y su audio',
  tabs: { note: 'notas', transcript: 'transcripción' },
  category: 'Categoría',
  notSure: 'no estoy seguro de qué fue',
  or: ' o ',
  noTranscript: 'Todavía no hay transcripción.',
  partSeam: (n, at) => `Parte ${n} · archivo nuevo en ${at}`,
  partNote: 'Las personas se etiquetan de nuevo en cada archivo, así que “Persona A” aquí puede ser alguien distinto a “Persona A” de arriba. Las notas ya lo tienen en cuenta.',
  mTranscribing: 'Transcribiendo. Esto sigue solo: puedes cerrar la pestaña.',
  mUploaded: 'Subida, esperando para enviarse a transcribir.',
  mHeld: 'Guardada y en espera: se usó el límite de uso justo de este mes. Se transcribirá sola cuando empiece el mes.',
  mNotesFailed: 'La transcripción llegó, pero las notas fallaron. Presiona “Escribir las notas” para intentarlo otra vez.',
  more: 'Más',
  moreActions: 'Más acciones',
  relabeled: (t: string) => `Categoría cambiada a «${t}». ¿Reescribir las notas para ese tipo? Tus notas actuales quedan si no lo haces.`,
  redoAsType: 'Reescribir las notas',
  keepNotes: 'Dejar estas notas',
  mEmpty: 'Nadie habló en esta grabación (quizás el lápiz quedó grabando en un bolsillo), así que no hay notas. Puedes borrarla.',
  mReady: 'La transcripción está lista y se están escribiendo las notas. Aparecen aquí en uno o dos minutos, y te avisamos por correo.',
  aiSummary: 'Resumen de la reunión con IA',
  byAi: 'Generado con IA',
  stillOpen: 'Sin resolver',
  decided: 'Decidido',
  nextActions: 'Próximos pasos',
  nDone: (d, n) => `${d}/${n} hechas`,
  priority: 'PRIORIDAD',
  missed: 'Quizás se te pasó',

  roomByRoom: 'Ambiente por ambiente',
  objections: 'Objeciones',
  signals: 'Señales de compra',
  wantTitle: 'Lo que realmente quieren',
  wantNote: 'Deducido de cómo reaccionaron, no de lo que dijeron.',
  sentiment: { loved: 'le encantó', liked: 'le gustó', neutral: 'neutral', disliked: 'no le gustó' },
  strength: { strong: 'fuerte', medium: 'media', weak: 'débil' },

  chatViewing: ['¿Qué les gustó de verdad?', '¿Cuáles fueron las objeciones?', '¿Dijeron que volverían?'],
  chatClinic: ['¿Qué hay que hacer hoy?', '¿Quién me debe algo?', '¿Qué quedé en hacer?'],
  chatDefault: ['¿A qué me comprometí?', '¿Qué se me pasó?', '¿Quedó algo sin resolver?'],
  noAnswer: 'No se pudo obtener una respuesta.',
  chatIntro: 'Las respuestas salen solo de esta grabación. Si no está ahí, lo dice en vez de adivinar.',
  chatPlaceholder: 'Pregunta sobre esta reunión…',
  ask: 'Preguntar',
}

const pt: AppCopy = {
  deleteFailed: 'Não foi possível apagar essa gravação.',
  notesFailed: 'Não foi possível escrever as notas.',
  noRecordingsIn: (dir) => `Nenhuma gravação em “${dir}”. Gravadores costumam guardar os arquivos numa subpasta — tente escolher essa.`,
  notMedia: 'Esses arquivos não são áudio ou vídeo que dê para ler aqui.',
  consentFirst: 'Confirme o consentimento primeiro. Na Flórida, todas as pessoas gravadas precisam concordar.',
  phasePreparing: 'Preparando o áudio',
  phaseSlot: 'Preparando o envio',
  phaseUploading: (note) => `Enviando · ${note}`,
  phasePiece: (i, n, size) => `Enviando parte ${i} de ${n} · ${size}, como está`,
  phaseSaving: 'Salvando',
  phaseSending: 'Enviando para transcrição',
  uploadUrlFailed: 'Não foi possível preparar o envio.',
  tooBigCompressed: (mb) =>
    `${mb} mesmo depois de comprimir — são várias horas de áudio. Divida em arquivos menores e envie separadamente; eles são juntados de novo.`,
  tooBigNoCompress: (mb) =>
    `${mb} passa do limite de 50 MB por arquivo, e este navegador não consegue comprimir áudio. Tente de novo no Chrome, que consegue.`,
  saveRecordingFailed: 'Não foi possível salvar a gravação.',
  transcribeFailed: 'Não foi possível iniciar a transcrição.',
  saveFailed: (status) => `Não foi possível salvar (${status}).`,
  untitled: 'Sem título',
  recordings: ['gravação', 'gravações'],

  brandTag: 'Grave. Entenda. Faça.',
  connectPen: 'Conectar a caneta',
  addFiles: 'Adicionar áudios',
  orDrag: 'ou arraste para cá',
  importTranscript: 'Importar uma transcrição',
  mUploadTitle: 'Adicione uma gravação',
  mUploadLede: 'Do celular, da caneta ou pelo WhatsApp. As notas chegam em alguns minutos.',
  mChoose: 'Escolher áudios',
  mChooseSub: 'Memos de voz, arquivos da caneta, qualquer gravação',
  mHistory: 'Histórico',
  mAll: 'Todas',
  mRecordingTitle: 'Gravação',
  iosPenTitle: 'Enviando da caneta? Leia isto antes',
  iosPenLede: 'O iPhone não consegue enviar direto da caneta. Copie a gravação para o iPhone e depois envie:',
  iosPenSteps: ['Abra o app Arquivos e toque em JUNO (a caneta), depois em RECORD.', 'Toque e segure a gravação e toque em Copiar.', 'Volte para No Meu iPhone, toque e segure um espaço vazio e toque em Colar.', 'Volte aqui, toque em Escolher áudios e depois Escolher Arquivos → No Meu iPhone.'],
  iosPenTip: 'No computador você pode enviar direto da caneta.',
  pausedTitle: (d) => `Pausado até ${d}`,
  pausedSub: 'Suas gravações continuam disponíveis. Retome o plano para adicionar novas.',
  resumeNow: 'Retomar agora',
  inviteFriends: 'Convide amigos e ganhe meses grátis',
  help: 'Ajuda',
  promoEyebrow: 'Novo: indique um colega',
  promoTitle: 'Dê um mês, ganhe um mês',
  promoLede: 'Compartilhe seu link com um colega. O primeiro mês dele é grátis, e você ganha um mês grátis por cada amigo que pagar.',
  promoTiers: [['1 amigo', '1 mês grátis'], ['3 amigos', '4 meses grátis'], ['10 amigos', 'um ano grátis']],
  promoGo: 'Ver meu link de convite',
  promoLater: 'Agora não',
  upWaiting: 'Na fila',
  upTitle: (done, total) => `Enviando · ${done} de ${total} prontas`,
  upKeepOpen: 'Continue usando o Juno normalmente. Deixe esta aba aberta até terminar.',
  upKeepOpenPhone: 'Mantenha o Juno aberto na tela até terminar.',
  upDoneTitle: (n) => (n === 1 ? 'Gravação enviada' : `${n} gravações enviadas`),
  upDoneBody: 'Enviaremos cada resumo por e-mail assim que estiver pronto, normalmente em poucos minutos.',
  upHeld: (n) => (n === 1 ? '1 aguarda horas de gravação.' : `${n} aguardam horas de gravação.`),
  upFailed: (n) => (n === 1 ? '1 não foi enviada:' : `${n} não foram enviadas:`),
  upShow: 'Ver arquivos',
  upHide: 'Ocultar arquivos',
  upClose: 'Fechar',
  upAskWa: 'Pergunte sobre elas no WhatsApp',
  upConnectWa: 'Conecte o WhatsApp para perguntar sobre elas',
  waCallTitle: 'Pergunte ao Juno pelo WhatsApp',
  waCallBody: 'Mande uma pergunta sobre qualquer reunião e receba a resposta em segundos. Toque em uma para testar.',
  waCallExamples: ['O que eu prometi enviar para eles?', 'Quais foram os próximos passos da minha última reunião?', 'O que disseram sobre o preço?'],
  waCallConnect: 'Conectar o WhatsApp',
  waCallConnectBody: 'Vincule seu telefone uma vez e depois mande ao Juno uma pergunta sobre qualquer reunião.',
  waCallHide: 'Ocultar',
  fbEyebrow: 'Dois minutos, três perguntas',
  fbTitle: 'Ajude a melhorar o Juno',
  fbQ1: 'Como você se sentiria se não pudesse mais usar o Juno Pen?',
  fbOpts: { very: 'Muito decepcionado/a', somewhat: 'Um pouco decepcionado/a', not: 'Nada decepcionado/a' },
  fbQ2: 'Qual é a única coisa que deveríamos corrigir ou adicionar?',
  fbQ3: 'Para quem você falaria do Juno, e para que diria que ele serve?',
  fbQ3Ph: 'ex.: “Qualquer corretor que faz visitas: ele escreve os follow-ups por você.”',
  fbOptional: 'opcional',
  fbSend: 'Enviar',
  fbSending: 'Enviando…',
  fbThanksTitle: 'Obrigado',
  fbThanks: 'Lemos todas as respostas. Se você escreveu algo que podemos melhorar, entraremos em contato.',
  fbDone: 'Voltar ao Juno',
  notionSend: 'Enviar para o Notion',
  importNotion: 'Importar do Notion',
  notionSending: 'Enviando…',
  notionOpen: 'Abrir no Notion',
  readOnlyTitle: 'Sua conta é somente leitura',
  readOnlySub: 'Seu plano terminou. Tudo o que você gravou continua disponível para ler; reative para adicionar gravações, buscar e conversar.',
  reactivate: 'Reativar',
  pillTrial: (n) => (n === 1 ? 'Teste: falta 1 dia' : `Teste: faltam ${n} dias`),
  pillEnding: (n) => (n === 1 ? 'Seu plano termina em 1 dia' : `Seu plano termina em ${n} dias`),
  pillReadOnly: 'Somente leitura',
  resuming: 'Retomando…',
  openWhatsApp: 'Abrir o WhatsApp',
  useWhatsApp: 'Usar o WhatsApp',
  waLinkedSub: 'Envie gravações, faça perguntas',
  waUnlinkedSub: 'Envie gravações do celular',
  home: 'Início',
  allRecordings: 'Todas as gravações',
  allRecordingsNav: 'Gravações',
  quote: ['Pequenos momentos.', 'Grandes avanços.'],
  chats: 'Conversas',
  newChat: 'Nova conversa',
  chatsEmpty: 'Pergunte algo na barra de busca e a conversa aparece aqui.',
  untitledChat: 'Conversa sem título',
  pages: 'Páginas',

  browseAria: 'Ver gravações e categorias',
  browse: 'Menu',
  waPhoneLinked: 'Envie uma gravação pelo WhatsApp',
  waPhoneUnlinked: 'Use o Juno Pen no WhatsApp',
  waPhoneLinkedSub: 'Conecte a caneta e compartilhe o arquivo na conversa',
  waPhoneUnlinkedSub: 'Envie gravações e faça perguntas pelo celular',
  loadError: (e) => `Não foi possível carregar as gravações: ${e}`,
  heldNotice: 'Você passou do limite de uso justo deste mês. Sua gravação foi salva e será transcrita quando o mês virar. Se precisar de mais, responda a qualquer e-mail do Juno Pen.',
  noPicker: 'Este navegador não consegue ler uma pasta diretamente. Use o Chrome ou o Edge para o “Conectar a caneta” com um clique, ou arraste os arquivos aqui embaixo.',
  runTitle: (n, dur) => `${n} gravações parecem uma só reunião de ${dur}.`,
  runBody: 'A caneta para aos 60 minutos e começa um arquivo novo.',
  untitledLower: 'sem título',
  joining: 'Juntando…',
  join: 'Juntar numa só reunião',
  close: 'Fechar',
  closeNav: 'Fechar o menu',
  chooseRecording: 'Escolha uma gravação à esquerda.',
  askPerson: (label) => `Mostre todas as conversas com @${label}`,

  recent: 'Gravações recentes',
  new: 'Nova',
  emptyCat: 'Nada nesta categoria.',
  showEverything: 'Ver tudo',
  emptyAll: ['Nada ainda. Conecte a caneta pelo USB, aperte ', ' e escolha a unidade que aparecer.'],
  status: {
    uploaded: 'enviada',
    held: 'faltam horas',
    transcribing: 'transcrevendo',
    transcribed: 'transcrita',
    noting: 'escrevendo notas',
    noted: 'pronta',
    error: 'erro',
  },
  parts: (n) => `${n} partes`,

  settings: 'Configurações',
  tour: 'Ver o tour',
  customers: 'Clientes',

  suggOpen: (n) => `O que eu ainda não fiz? (${n} pendentes)`,
  suggClient: (c) => `O que ${c} quer de verdade?`,
  suggCategory: (c) => `Resuma minhas gravações de ${c}`,
  suggOwes: 'Quem está me devendo algo?',
  suggFallback: ['O que eu deixei passar esta semana?', 'O que ficou sem resolver?', 'Com o que eu me comprometi?'],
  searchPlaceholder: 'Pergunte qualquer coisa… digite @ para uma pessoa ou gravação',
  searchAria: 'Pergunte ao seu arquivo',
  tryAsking: 'Experimente perguntar',

  clickRename: 'Clique para renomear',
  renameFailed: 'O novo nome não foi salvo — o anterior voltou.',
  working: 'Trabalhando…',
  setCategory: 'Escolher categoria',
  typeOwn: 'Digite a sua…',

  addRecording: 'Adicionar uma gravação',
  doneTitle: 'Avisamos por e-mail quando estiver pronta.',
  doneBody: 'Transcrever e escrever as notas leva alguns minutos. Pode fechar isto — o resumo chega sozinho no seu e-mail.',
  keepOpen: 'Deixe esta aba aberta até terminar — sair do Safari interrompe o envio.',
  remove: (name) => `Remover ${name}`,
  consentPhone: 'Todas as pessoas gravadas concordaram, e não há informação médica ou de pacientes.',
  consentDesk: 'Todas as pessoas gravadas concordaram, e esta gravação não contém informação médica ou de pacientes.',
  addN: (n) => (n > 1 ? `Adicionar ${n} gravações` : 'Adicionar gravação'),
  nameLater: 'Depois você pode dizer com quem foi.',
  done: 'Pronto',
  onPen: (n, pen) => `${n} em “${pen}”`,
  readyImport: 'Pronto para importar',
  clear: 'limpar',
  whoOnCall: 'Quem estava nesta reunião (opcional)',
  whoHint: 'Se deixar vazio, as notas sugerem quem foi ouvido.',
  importN: (n) => (n ? `Importar ${n} e transcrever` : 'Importar e transcrever'),

  noPartTranscript: 'Esta parte ainda não tem transcrição.',
  speakers: ['pessoa', 'pessoas'],
  aiSummarised: 'Resumido por IA',
  imported: 'Importada',
  transcribed: 'Transcrita',
  chipTranscribing: 'Transcrevendo',
  chipNoting: 'Escrevendo notas',
  chipError: 'Algo falhou',
  chipHeld: 'Esperando horas',
  joinedNote: (n) => `A caneta chegou ao limite de 60 minutos por arquivo, então esta reunião chegou em ${n} partes. Elas são lidas como uma só — as gravações continuam aqui.`,
  separating: 'Separando…',
  separate: 'Separar de novo',
  redoNotes: 'Refazer notas',
  writeNotes: 'Escrever as notas',
  hideChat: 'Esconder conversa',
  askMeeting: 'Perguntar sobre a reunião',
  deleteForGood: 'Apagar de vez?',
  keep: 'Manter',
  delete: 'Apagar',
  deleteTitle: 'Apagar esta gravação e o áudio',
  tabs: { note: 'notas', transcript: 'transcrição' },
  category: 'Categoria',
  notSure: 'não sei bem o que foi',
  or: ' ou ',
  noTranscript: 'Ainda não há transcrição.',
  partSeam: (n, at) => `Parte ${n} · arquivo novo em ${at}`,
  partNote: 'As pessoas são rotuladas de novo em cada arquivo, então a “Pessoa A” aqui pode ser alguém diferente da “Pessoa A” acima. As notas já levam isso em conta.',
  mTranscribing: 'Transcrevendo. Isso continua sozinho — pode fechar a aba.',
  mUploaded: 'Enviada, esperando para ir para a transcrição.',
  mHeld: 'Salva e em espera: o limite de uso justo deste mês acabou. Ela será transcrita sozinha quando o mês virar.',
  mNotesFailed: 'A transcrição chegou, mas as notas falharam. Aperte “Escrever as notas” para tentar de novo.',
  more: 'Mais',
  moreActions: 'Mais ações',
  relabeled: (t: string) => `Categoria alterada para “${t}”. Reescrever as notas para esse tipo? Suas notas atuais ficam se você não fizer isso.`,
  redoAsType: 'Reescrever as notas',
  keepNotes: 'Manter estas notas',
  mEmpty: 'Ninguém falou nesta gravação (talvez a caneta tenha ficado gravando no bolso), então não há notas. Você pode apagá-la.',
  mReady: 'A transcrição está pronta e as notas estão sendo escritas. Elas aparecem aqui em um ou dois minutos, e avisamos você por e-mail.',
  aiSummary: 'Resumo da reunião por IA',
  byAi: 'Gerado por IA',
  stillOpen: 'Em aberto',
  decided: 'Decidido',
  nextActions: 'Próximos passos',
  nDone: (d, n) => `${d}/${n} feitas`,
  priority: 'PRIORIDADE',
  missed: 'Talvez tenha passado batido',

  roomByRoom: 'Cômodo por cômodo',
  objections: 'Objeções',
  signals: 'Sinais de compra',
  wantTitle: 'O que eles querem de verdade',
  wantNote: 'Deduzido das reações, não do que disseram.',
  sentiment: { loved: 'adorou', liked: 'gostou', neutral: 'neutro', disliked: 'não gostou' },
  strength: { strong: 'forte', medium: 'médio', weak: 'fraco' },

  chatViewing: ['Do que eles gostaram de verdade?', 'Quais foram as objeções?', 'Disseram que voltariam?'],
  chatClinic: ['O que precisa ser feito hoje?', 'Quem está me devendo algo?', 'O que eu fiquei de acompanhar?'],
  chatDefault: ['Com o que eu me comprometi?', 'O que eu deixei passar?', 'Ficou algo sem resolver?'],
  noAnswer: 'Não foi possível obter uma resposta.',
  chatIntro: 'As respostas vêm só desta gravação. Se não estiver nela, ele diz em vez de adivinhar.',
  chatPlaceholder: 'Pergunte sobre esta reunião…',
  ask: 'Perguntar',
}

export const APP_COPY: Copy<AppCopy> = { en, es, pt }
