export interface ReportData {
  company: string
  slug: string
  domain: string
  industry: string
  description: string
  generatedDate: string
  paidKeywords: number
  monthlyClicks: number
  monthlyBudgetLow: number
  monthlyBudgetHigh: number
  effectiveCPC: number
  industryAvgCPC: number
  industryAvgCTR: number
  industryAvgCVR: number
  industryAvgCPL: number
  industryAvgWaste: number
  topKeywords: {
    keyword: string
    volume: string
    cpc: number
    clickShare: number
    intent: 'high' | 'medium' | 'low'
  }[]
  competitors: {
    domain: string
    keywords: string
    monthlyClicks: string
    budget: string
    commonKeywords: number
    overlapPercent: number
  }[]
  insights: {
    title: string
    metric: string
    body: string
    type: 'warning' | 'danger' | 'info'
  }[]
  trafficSplit: { paid: number; organic: number }
  adCopy: { headline: string; description: string; keyword: string }[]
  organic: {
    keywords: number
    monthlyClicks: number
    estClickValue: number
    page1Keywords: number
    fallingOffPage1: number
    topKeywords: { keyword: string; clicks: string; type: 'informational' | 'commercial' }[]
    competitors: { domain: string; keywords: string }[]
  }
}

export const reports: Record<string, ReportData> = {
  remofirst: {
    company: 'RemoFirst',
    slug: 'remofirst',
    domain: 'remofirst.com',
    industry: 'HR Tech / Employer of Record',
    description: 'Global employer of record platform enabling companies to hire in 180+ countries.',
    generatedDate: 'May 2026',
    paidKeywords: 4100,
    monthlyClicks: 8700,
    monthlyBudgetLow: 244000,
    monthlyBudgetHigh: 264000,
    effectiveCPC: 30.34,
    industryAvgCPC: 11.50,
    industryAvgCTR: 3.2,
    industryAvgCVR: 3.5,
    industryAvgCPL: 280,
    industryAvgWaste: 36.1,
    topKeywords: [
      { keyword: 'hr', volume: '61.1K', cpc: 2.19, clickShare: 3.47, intent: 'low' },
      { keyword: 'payroll', volume: '48.2K', cpc: 5.88, clickShare: 17.0, intent: 'low' },
      { keyword: 'outsourcing', volume: '37.2K', cpc: 6.53, clickShare: 2.46, intent: 'medium' },
      { keyword: 'employer', volume: '31.8K', cpc: 0.69, clickShare: 2.12, intent: 'low' },
      { keyword: 'applicant tracking system', volume: '4.3K', cpc: 171.93, clickShare: 1.2, intent: 'low' },
      { keyword: 'payroll services', volume: '4.5K', cpc: 118.48, clickShare: 1.8, intent: 'medium' },
    ],
    competitors: [
      { domain: 'oysterhr.com', keywords: '13.1K', monthlyClicks: '34.9K', budget: '$562K', commonKeywords: 1360, overlapPercent: 33 },
      { domain: 'deel.com', keywords: '14.2K', monthlyClicks: '424K', budget: '$3.96M', commonKeywords: 2880, overlapPercent: 70 },
      { domain: 'atlashxm.com', keywords: '3.3K', monthlyClicks: '109', budget: '$111K', commonKeywords: 760, overlapPercent: 19 },
      { domain: 'globalization-partners.com', keywords: '64.8K', monthlyClicks: '50K', budget: '$1.02M', commonKeywords: 1950, overlapPercent: 48 },
    ],
    insights: [
      {
        title: 'Effective CPC is ~3x the industry average',
        metric: '$30 vs $11.50',
        body: 'Based on estimated auction data, RemoFirst\'s effective cost per click appears to be approximately 2.6x the HR Tech industry benchmark. Deel, bidding on many of the same terms, achieves roughly $9 per click — suggesting higher Quality Scores or better-optimized landing pages that earn a Google discount.',
        type: 'danger',
      },
      {
        title: '~70% keyword overlap with a competitor spending 15x more',
        metric: '2,880 shared keywords with Deel',
        body: 'An estimated 70% of RemoFirst\'s paid keyword portfolio overlaps with Deel, who operates with roughly 15x the ad budget. Competing head-to-head on shared terms against a dramatically larger budget means getting outbid on most auctions. The opportunity: find high-intent keywords where Deel isn\'t competing.',
        type: 'warning',
      },
      {
        title: 'High-CPC keywords with mismatched buyer intent',
        metric: '$172/click on "applicant tracking system"',
        body: 'SpyFu shows bidding activity on "applicant tracking system" at an estimated $172 per click. People searching this term are typically looking for tools like Greenhouse or Lever — not an EOR. This could be a deliberate top-of-funnel play, but it\'s a high-risk bet unless CRM data shows these searchers convert to EOR contracts at an outsized rate.',
        type: 'danger',
      },
      {
        title: 'Highest-exposure keyword attracts mixed intent',
        metric: '"payroll" — est. 17% of paid clicks',
        body: '"Payroll" appears to be the single highest-exposure auction term, capturing an estimated 17% of all paid click activity. But this keyword is massively generic — it attracts people searching for payroll calculators, payroll jobs, ADP login help, and salary tools alongside actual EOR buyers. The signal-to-noise ratio is low.',
        type: 'warning',
      },
      {
        title: 'Brand defense may be inflating costs',
        metric: 'Est. $37 CPC on own brand name',
        body: 'External data suggests RemoFirst\'s own brand keyword carries a ~$37 CPC — significantly above what branded terms typically cost. This usually means competitors are actively bidding on your brand name, forcing you to pay a premium to defend your own search results. Worth auditing which competitors are triggering ads on "remofirst" searches.',
        type: 'info',
      },
    ],
    trafficSplit: { paid: 25.35, organic: 74.65 },
    adCopy: [
      {
        keyword: 'payroll',
        headline: 'Hire global talent with RemoFirst - Global Payroll & Compliance',
        description: 'Use RemoFirst as your Employer of Record to onboard employees anywhere in... Get Pricing · Employer Of Record Payroll Services · EOR Services · Full-Time & Contractor',
      },
      {
        keyword: 'payroll',
        headline: 'Payroll Management Made Easy',
        description: 'World\'s Most Affordable EOR — Hire anywhere without setting up a local entity. Starts at $199 per employee per month. 180+ countries. Book Your Free Demo Today.',
      },
    ],
    organic: {
      keywords: 11020,
      monthlyClicks: 10800,
      estClickValue: 109000,
      page1Keywords: 1806,
      fallingOffPage1: 425,
      topKeywords: [
        { keyword: 'telecommuting', clicks: '1K', type: 'informational' },
        { keyword: 'employee', clicks: '380', type: 'informational' },
        { keyword: 'fisa', clicks: '270', type: 'informational' },
        { keyword: 'eor', clicks: '270', type: 'commercial' },
        { keyword: 'tin', clicks: '210', type: 'informational' },
        { keyword: 'wages definition', clicks: '150', type: 'informational' },
        { keyword: 'independent contractor payment schedule', clicks: '115', type: 'informational' },
        { keyword: 'what is a freelancer', clicks: '95', type: 'informational' },
      ],
      competitors: [
        { domain: 'usemultiplier.com', keywords: '38.4K' },
        { domain: 'asanify.com', keywords: '28K' },
        { domain: 'velocityglobal.com', keywords: '28.3K' },
        { domain: 'rivermate.com', keywords: '18.7K' },
      ],
    },
  },
  karmacheck: {
    company: 'KarmaCheck',
    slug: 'karmacheck',
    domain: 'karmacheck.com',
    industry: 'HR Tech / Background Screening',
    description: 'AI-powered background check and credential verification platform for employers and staffing firms.',
    generatedDate: 'May 2026',
    paidKeywords: 406,
    monthlyClicks: 5490,
    monthlyBudgetLow: 10000,
    monthlyBudgetHigh: 12800,
    effectiveCPC: 2.33,
    industryAvgCPC: 4.50,
    industryAvgCTR: 5.5,
    industryAvgCVR: 3.8,
    industryAvgCPL: 120,
    industryAvgWaste: 30,
    topKeywords: [
      { keyword: 'background check for employment', volume: '3.3K', cpc: 4.44, clickShare: 10.0, intent: 'high' },
      { keyword: 'checkr', volume: '22.6K', cpc: 0.27, clickShare: 0.9, intent: 'low' },
      { keyword: 'sterling background check', volume: '5.5K', cpc: 1.15, clickShare: 2.6, intent: 'low' },
      { keyword: 'checkpeople', volume: '5.3K', cpc: 0.79, clickShare: 3.4, intent: 'low' },
      { keyword: 'background check', volume: '301K', cpc: 3.50, clickShare: 5.2, intent: 'high' },
      { keyword: 'pre employment background check', volume: '2.9K', cpc: 5.20, clickShare: 2.1, intent: 'high' },
    ],
    competitors: [
      { domain: 'checkr.com', keywords: '15.5K', monthlyClicks: '510K', budget: '$540K', commonKeywords: 106, overlapPercent: 55 },
      { domain: 'backgroundchecks.com', keywords: '7.78K', monthlyClicks: '290K', budget: '$450K', commonKeywords: 95, overlapPercent: 45 },
      { domain: 'hireright.com', keywords: '895', monthlyClicks: '18K', budget: '$35K', commonKeywords: 72, overlapPercent: 30 },
      { domain: 'certn.co', keywords: '748', monthlyClicks: '12K', budget: '$22K', commonKeywords: 58, overlapPercent: 25 },
    ],
    insights: [
      {
        title: 'Competitor brand bidding is the core paid strategy',
        metric: '3 of top 4 keywords are competitor brands',
        body: 'KarmaCheck\'s most-clicked paid keywords are competitor brands — "checkr," "sterling background check," and "checkpeople." At CPCs of $0.27–$1.15, these clicks are cheap. But competitor brand searchers typically have an existing vendor relationship. Without CRM data showing close rates on conquesting clicks vs. category keywords, it\'s impossible to know if this is efficient acquisition or just busy traffic.',
        type: 'warning',
      },
      {
        title: 'Possible B2C intent mismatch on "checkpeople"',
        metric: 'Est. $146/mo on a consumer people-search brand',
        body: 'CheckPeople is a consumer people-search tool — searchers are looking to look up individuals online, not run employer background checks. KarmaCheck appears to be spending an estimated $146/month on this keyword. The CPC is low ($0.79), but if conversion rate is near zero because of intent mismatch, even cheap clicks are waste. CRM data would confirm whether any of these clicks ever became pipeline.',
        type: 'danger',
      },
      {
        title: 'Organic search is nearly nonexistent',
        metric: '360 SEO clicks/mo vs 5,490 paid',
        body: 'Only ~6% of KarmaCheck\'s search traffic comes from organic results, with just 61 keywords on page 1. By comparison, backgroundchecks.com has 26,100 organic keywords generating 37,500 monthly clicks. There are 55 keywords in "almost there" position (ranks 11–18) that could reach page 1 with targeted content — each one reduces paid dependency permanently.',
        type: 'danger',
      },
      {
        title: 'SpyFu flags ~36% of paid keywords as potential waste',
        metric: '145 of 406 keywords',
        body: 'SpyFu\'s analysis flags approximately 36% of KarmaCheck\'s paid keyword portfolio as potential ad waste. At an estimated total budget of $12.8K/month, that could mean ~$4,600/month going to keywords unlikely to convert. The real answer depends on CRM data — some "wasteful" keywords by click metrics might actually produce high-value deals that justify the spend.',
        type: 'warning',
      },
      {
        title: '$12.8K budget vs. competitors spending 40x more',
        metric: '~1.2% of paid search traffic share',
        body: 'KarmaCheck captures roughly 1.2% of paid search traffic in its competitive set, while Checkr commands ~51% with an estimated $540K/month budget. With a ~42x budget gap, every dollar needs to work harder. The current low-CPC conquesting strategy keeps costs down, but 570 keywords competitors bid on that KarmaCheck doesn\'t represent potential gaps in coverage.',
        type: 'info',
      },
    ],
    trafficSplit: { paid: 60.65, organic: 39.35 },
    adCopy: [
      {
        keyword: 'background check for employment',
        headline: 'AI-Powered Background Checks — Faster, More Accurate Screening',
        description: 'Modernize your screening process with KarmaCheck. SOC 2 certified. API-first platform integrates with your ATS. Results in hours, not days.',
      },
      {
        keyword: 'checkr',
        headline: 'Looking for a Checkr Alternative? — Try KarmaCheck',
        description: 'Faster turnaround, better accuracy, modern API. Switch to KarmaCheck and reduce time-to-hire. Background checks built for high-volume hiring.',
      },
    ],
    organic: {
      keywords: 821,
      monthlyClicks: 360,
      estClickValue: 9130,
      page1Keywords: 61,
      fallingOffPage1: 2,
      topKeywords: [
        { keyword: 'karmacheck', clicks: '50', type: 'commercial' },
        { keyword: 'verified credentials', clicks: '20', type: 'commercial' },
        { keyword: 'karma login', clicks: '16', type: 'commercial' },
        { keyword: 'healthcare background checks', clicks: '8', type: 'commercial' },
        { keyword: 'how to verify employee education', clicks: '6', type: 'informational' },
        { keyword: 'what is needed to run a background check', clicks: '5', type: 'informational' },
        { keyword: 'background check.com', clicks: '6', type: 'informational' },
        { keyword: 'smart background check', clicks: '3', type: 'informational' },
      ],
      competitors: [
        { domain: 'backgroundchecks.com', keywords: '26.1K' },
        { domain: 'accurate.com', keywords: '26.3K' },
        { domain: 'securecheck360.com', keywords: '2.51K' },
        { domain: '4slonline.com', keywords: '1.04K' },
      ],
    },
  },
  safetywing: {
    company: 'SafetyWing',
    slug: 'safetywing',
    domain: 'safetywing.com',
    industry: 'Insurtech / Remote Worker Insurance',
    description: 'Insurance platform for remote workers, digital nomads, and distributed teams — health insurance and travel medical coverage worldwide.',
    generatedDate: 'May 2026',
    paidKeywords: 221,
    monthlyClicks: 238,
    monthlyBudgetLow: 2000,
    monthlyBudgetHigh: 2650,
    effectiveCPC: 11.13,
    industryAvgCPC: 12.00,
    industryAvgCTR: 3.5,
    industryAvgCVR: 2.8,
    industryAvgCPL: 85,
    industryAvgWaste: 35,
    topKeywords: [
      { keyword: 'international health insurance', volume: '3K', cpc: 7.46, clickShare: 20.0, intent: 'high' },
      { keyword: 'nomad travel insurance', volume: '1.1K', cpc: 29.43, clickShare: 15.0, intent: 'high' },
      { keyword: 'health insurance for overseas', volume: '1.5K', cpc: 9.48, clickShare: 8.0, intent: 'high' },
      { keyword: 'health insurance for abroad', volume: '1.5K', cpc: 6.30, clickShare: 6.0, intent: 'high' },
      { keyword: 'safetywing', volume: '1.3K', cpc: 0.45, clickShare: 12.0, intent: 'high' },
      { keyword: 'health insurance for remote workers', volume: '720', cpc: 15.80, clickShare: 4.5, intent: 'high' },
    ],
    competitors: [
      { domain: 'joinarla.com', keywords: '854', monthlyClicks: '24.1K', budget: '$230K', commonKeywords: 22, overlapPercent: 16 },
      { domain: 'internationalinsurance.com', keywords: '2.57K', monthlyClicks: '17.2K', budget: '$153K', commonKeywords: 37, overlapPercent: 26 },
      { domain: 'axaglobalhealthcare.com', keywords: '907', monthlyClicks: '17.3K', budget: '$68.8K', commonKeywords: 24, overlapPercent: 17 },
      { domain: 'roundstoneinsurance.com', keywords: '138', monthlyClicks: '2.11K', budget: '$14.1K', commonKeywords: 11, overlapPercent: 8 },
    ],
    insights: [
      {
        title: '$2.65K/month PPC in a category where competitors spend $230K',
        metric: 'Est. 87x budget gap with largest paid competitor',
        body: 'SafetyWing\'s estimated paid search budget of $2.65K/month generates roughly 238 clicks. Meanwhile, joinarla.com spends an estimated $230K/month and internationalinsurance.com ~$153K. With only 43 core keywords shared across competitors, SafetyWing is barely participating in paid search. This is either a deliberate organic-first strategy or a major gap — CRM data would reveal whether those 238 paid clicks convert well enough to justify scaling up.',
        type: 'danger',
      },
      {
        title: '"nomad travel insurance" at $29/click may consume most of the budget',
        metric: 'Est. $29.43 CPC — 2.5x the industry average',
        body: 'SpyFu estimates the "nomad travel insurance" keyword at $29.43 per click — roughly 85 clicks would exhaust the entire monthly PPC budget. This extreme concentration in one high-CPC term means the paid channel lives or dies on a single keyword\'s performance. Without CRM data, there\'s no way to know if those $29 clicks are producing high-LTV policyholders or just expensive bounces.',
        type: 'warning',
      },
      {
        title: '"nomad insurance" is losing organic ranks across multiple positions',
        metric: '5 ranking drops, up to 163 positions lost',
        body: 'SpyFu shows "nomad insurance" — SafetyWing\'s core category keyword — dropping ranks across at least 5 tracked positions, with losses of up to 163 rank positions. This is one of the most commercially valuable organic terms in their portfolio. If this decline continues without paid coverage to compensate, competitors will capture that search demand. The current $2.65K PPC budget is not a safety net for organic erosion at this scale.',
        type: 'danger',
      },
      {
        title: '3,860 missing organic keywords that competitors rank for',
        metric: 'Est. 230K monthly search volume uncaptured',
        body: 'SpyFu\'s Kombat analysis shows SafetyWing doesn\'t rank for 3,860 keywords (representing an estimated 230K monthly searches) where competitors imglobal.com and travelexinsurance.com already rank. These are potential free clicks that require content investment, not ad spend. With 309 keywords already in "almost there" position (ranks 11–18), some quick wins may be within reach.',
        type: 'info',
      },
      {
        title: 'Organic drives 92% of search traffic — strong but concentrated',
        metric: '2,690 SEO clicks vs 238 paid clicks',
        body: 'SafetyWing has a healthy organic-first profile with 7,925 ranked keywords and 459 on page 1. But top organic traffic is heavily branded — "safetywing" alone drives 210 of 2,690 monthly SEO clicks. If organic ranks erode on commercial terms like "nomad insurance," there\'s almost no paid infrastructure to absorb the lost traffic. The question CRM data answers: are organic visitors converting at a rate that justifies keeping paid minimal?',
        type: 'info',
      },
    ],
    trafficSplit: { paid: 8.1, organic: 91.9 },
    adCopy: [
      {
        keyword: 'international health insurance',
        headline: 'Health Insurance for Remote Teams — SafetyWing Global Coverage',
        description: 'Insurance designed for remote workers and digital nomads. Coverage in 175+ countries. Plans starting at $45/month. No long-term contracts required.',
      },
      {
        keyword: 'nomad travel insurance',
        headline: 'Travel Medical Insurance for Nomads — SafetyWing',
        description: 'Built for people who live and work abroad. Instant signup, monthly billing, coverage that travels with you. Trusted by remote workers worldwide.',
      },
    ],
    organic: {
      keywords: 7925,
      monthlyClicks: 2690,
      estClickValue: 105000,
      page1Keywords: 459,
      fallingOffPage1: 38,
      topKeywords: [
        { keyword: 'safetywing', clicks: '210', type: 'commercial' },
        { keyword: 'nomad insurance', clicks: '165', type: 'commercial' },
        { keyword: 'safety insurance', clicks: '130', type: 'informational' },
        { keyword: 'nomad health', clicks: '125', type: 'commercial' },
        { keyword: 'health insurance for remote workers', clicks: '28', type: 'commercial' },
        { keyword: 'nomad travel insurance', clicks: '22', type: 'commercial' },
        { keyword: 'medical insurance foreign', clicks: '20', type: 'commercial' },
        { keyword: 'holiday health insurance', clicks: '8', type: 'informational' },
      ],
      competitors: [
        { domain: 'travelguard.com', keywords: '27.3K' },
        { domain: 'imglobal.com', keywords: '25.3K' },
        { domain: 'travelexinsurance.com', keywords: '10.7K' },
        { domain: 'travelinsured.com', keywords: '9.22K' },
      ],
    },
  },
  demostack: {
    company: 'Demostack',
    slug: 'demostack',
    domain: 'demostack.com',
    industry: 'Sales Tech / Interactive Demo Software',
    description: 'Interactive product demo platform that lets sales teams create and deliver personalized live demos and leave-behinds.',
    generatedDate: 'May 2026',
    paidKeywords: 222,
    monthlyClicks: 44,
    monthlyBudgetLow: 0,
    monthlyBudgetHigh: 1000,
    effectiveCPC: 1.55,
    industryAvgCPC: 8.50,
    industryAvgCTR: 3.5,
    industryAvgCVR: 3.0,
    industryAvgCPL: 200,
    industryAvgWaste: 32,
    topKeywords: [
      { keyword: 'demo video', volume: '8.1K', cpc: 1.95, clickShare: 28.0, intent: 'medium' },
      { keyword: 'product demo', volume: '2.4K', cpc: 1.94, clickShare: 22.0, intent: 'high' },
      { keyword: 'product demonstration', volume: '1.1K', cpc: 1.33, clickShare: 8.0, intent: 'high' },
      { keyword: 'live demo', volume: '3.2K', cpc: 0.99, clickShare: 6.0, intent: 'high' },
      { keyword: 'mindtickle', volume: '5.4K', cpc: 0.00, clickShare: 4.0, intent: 'low' },
      { keyword: 'interactive demo', volume: '1.8K', cpc: 2.10, clickShare: 3.0, intent: 'high' },
    ],
    competitors: [
      { domain: 'saleo.io', keywords: '781', monthlyClicks: '3.64K', budget: '$23K', commonKeywords: 46, overlapPercent: 21 },
      { domain: 'walnut.io', keywords: '743', monthlyClicks: '70', budget: '$2.2K', commonKeywords: 43, overlapPercent: 19 },
      { domain: 'goconsensus.com', keywords: '1.13K', monthlyClicks: '555', budget: '$0', commonKeywords: 42, overlapPercent: 19 },
      { domain: 'storylane.io', keywords: '959', monthlyClicks: '1.49K', budget: '$0', commonKeywords: 32, overlapPercent: 14 },
    ],
    insights: [
      {
        title: 'Paid search appears to be switched off',
        metric: '$0 budget vs $23K for closest paid competitor',
        body: 'SpyFu shows Demostack\'s estimated PPC budget at $0, despite 5+ years of ad history and 222 keywords still indexed. Meanwhile, Saleo.io spends an estimated $23K/month and captures 3,640 paid clicks. If high-intent searches like "product demo software" and "interactive demo" are going exclusively to competitors, Demostack is invisible to actively researching buyers in those moments.',
        type: 'danger',
      },
      {
        title: 'Core category keywords falling off organic page 1',
        metric: '"interactive demo software" dropped 10 ranks',
        body: '"Interactive demo software" fell from page 1 to page 2, "presales software" dropped 6 ranks, and "customer-led growth" lost 12 positions. These are commercial-intent terms that signal active buyers. Without paid search as a safety net, each organic rank drop means competitors pick up those impressions with no fallback.',
        type: 'danger',
      },
      {
        title: '9% organic traffic share in a crowded category',
        metric: '577 clicks/mo vs 6,580 for Walnut',
        body: 'In a 5-competitor organic set, Demostack commands roughly 9% of search traffic. GoConsensus holds 39% with 3,690 keywords and Walnut holds 35% with 3,300 keywords. Both have roughly 4x Demostack\'s keyword footprint. Without paid to supplement, this organic gap translates directly to a pipeline share gap.',
        type: 'warning',
      },
      {
        title: '108 keywords at ranks 11-18 could break onto page 1',
        metric: '146 on page 1 now, 108 almost there',
        body: 'SpyFu identifies 108 keywords in the "almost there" range (ranks 11-18), just off page 1. With 146 keywords currently on page 1 generating 577 monthly clicks, moving even 20-30 of these onto page 1 could meaningfully increase organic visibility. These are lower-effort wins compared to building rankings from scratch, and they don\'t require ad spend.',
        type: 'info',
      },
      {
        title: '193 keyword gaps where competitors rank and Demostack doesn\'t',
        metric: 'Est. 8,850 monthly search volume uncaptured',
        body: 'SpyFu\'s Kombat analysis shows 193 organic keywords where competitors like GoConsensus and Walnut rank but Demostack has no presence. These represent an estimated 8,850 monthly searches worth of uncaptured demand. With paid search at $0, these gaps mean entire segments of buyer search behavior are invisible to Demostack.',
        type: 'warning',
      },
    ],
    trafficSplit: { paid: 7, organic: 93 },
    adCopy: [
      {
        keyword: 'product demo',
        headline: 'Interactive Product Demos - Personalized Demo Experiences',
        description: 'Build custom product demos in minutes. No engineering required. Create, deliver, and track interactive demos that close deals faster.',
      },
      {
        keyword: 'demo video',
        headline: 'Product Demo Software - Demostack',
        description: 'Stop relying on live demos alone. Create interactive, self-guided product experiences your buyers can explore on their own time.',
      },
    ],
    organic: {
      keywords: 849,
      monthlyClicks: 577,
      estClickValue: 12800,
      page1Keywords: 146,
      fallingOffPage1: 20,
      topKeywords: [
        { keyword: 'demo', clicks: '190', type: 'informational' },
        { keyword: 'demostack', clicks: '60', type: 'commercial' },
        { keyword: 'pochunter', clicks: '26', type: 'informational' },
        { keyword: 'software demonstration', clicks: '20', type: 'commercial' },
        { keyword: 'solution selling', clicks: '18', type: 'informational' },
        { keyword: 'demo software', clicks: '16', type: 'commercial' },
        { keyword: 'sales velocity', clicks: '13', type: 'informational' },
        { keyword: 'sales groups', clicks: '9', type: 'informational' },
      ],
      competitors: [
        { domain: 'goconsensus.com', keywords: '3.69K' },
        { domain: 'walnut.io', keywords: '3.3K' },
        { domain: 'demoboost.com', keywords: '1.12K' },
        { domain: 'testbox.com', keywords: '550' },
      ],
    },
  },
  miter: {
    company: 'Miter',
    slug: 'miter',
    domain: 'miter.com',
    industry: 'Construction Tech / Payroll & Compliance',
    description: 'Payroll, HR, expenses, and field operations software built for construction contractors.',
    generatedDate: 'May 2026',
    paidKeywords: 814,
    monthlyClicks: 786,
    monthlyBudgetLow: 18000,
    monthlyBudgetHigh: 19800,
    effectiveCPC: 25.19,
    industryAvgCPC: 18.00,
    industryAvgCTR: 3.0,
    industryAvgCVR: 2.5,
    industryAvgCPL: 300,
    industryAvgWaste: 35,
    topKeywords: [
      { keyword: 'certified payroll', volume: '5.4K', cpc: 7.22, clickShare: 18.0, intent: 'high' },
      { keyword: 'construction project management software', volume: '2.9K', cpc: 20.36, clickShare: 15.0, intent: 'medium' },
      { keyword: 'project time tracking software', volume: '1.8K', cpc: 15.29, clickShare: 5.0, intent: 'medium' },
      { keyword: 'prevailing wage rates', volume: '3.6K', cpc: 1.18, clickShare: 8.0, intent: 'high' },
      { keyword: 'miter', volume: '7.8K', cpc: 0.46, clickShare: 3.0, intent: 'low' },
      { keyword: 'construction payroll', volume: '1.2K', cpc: 12.50, clickShare: 6.0, intent: 'high' },
    ],
    competitors: [
      { domain: 'hcmtradeseal.com', keywords: '200', monthlyClicks: '1.11K', budget: '$21.5K', commonKeywords: 53, overlapPercent: 7 },
      { domain: 'rippling.com', keywords: '8.2K', monthlyClicks: '42K', budget: '$320K', commonKeywords: 35, overlapPercent: 4 },
      { domain: 'hh2.com', keywords: '383', monthlyClicks: '6.28K', budget: '$0', commonKeywords: 42, overlapPercent: 5 },
      { domain: 'dili.com', keywords: '189', monthlyClicks: '641', budget: '$0', commonKeywords: 16, overlapPercent: 2 },
    ],
    insights: [
      {
        title: '83% of paid keywords flagged as potential waste',
        metric: '679 of 814 keywords',
        body: 'SpyFu\'s Kombat analysis flags 679 of Miter\'s 814 paid keywords as potential ad waste, representing an estimated 25,100 monthly clicks. At a $19.8K/month budget, the majority of spend may be going to keywords that don\'t convert. The real answer requires CRM data to see which of those clicks became pipeline, but the flag rate is significantly above the 35% construction tech industry benchmark.',
        type: 'danger',
      },
      {
        title: 'Brand name "miter" creates massive intent dilution',
        metric: '7,800 monthly searches, mostly woodworking',
        body: '"Miter" is a common woodworking and construction term. People searching "miter" are overwhelmingly looking for miter saws, miter joints, or miter boxes. Both organic (1,300 clicks/mo) and paid traffic on this keyword are likely heavily diluted with irrelevant intent. Without CRM data, it\'s impossible to know what percentage of "miter" clicks are actually looking for payroll software vs. power tools.',
        type: 'warning',
      },
      {
        title: '$20+ CPCs on broad software terms',
        metric: '"construction project management software" at $20.36/click',
        body: 'Miter is bidding on broad category terms like "construction project management software" ($20.36 CPC) and "project time tracking software" ($15.29 CPC). These terms attract buyers looking for general PM and time tracking tools, not specifically payroll compliance. At these CPCs, even a small percentage of mismatched intent means thousands in wasted spend each month.',
        type: 'warning',
      },
      {
        title: 'Organic growth is strong and accelerating',
        metric: '2,514 newly ranked keywords, +22.3K rank improvement',
        body: 'Miter\'s organic footprint is expanding rapidly: 3,518 keywords (up significantly), 2,514 newly ranked keywords, and a sum rank improvement of +22.3K in the last month. Content like "DAS 140 & 142 Forms" and "How to calculate fringe benefits" is pulling in high-intent contractor traffic for free. With 184 keywords in "almost there" position (ranks 11-18), there\'s room to grow organic further and reduce paid dependency.',
        type: 'info',
      },
      {
        title: '254 organic keyword gaps vs competitors',
        metric: 'Est. 16,500 monthly search volume uncaptured',
        body: 'SpyFu\'s Kombat analysis shows 254 organic keywords where competitors like eBacon, Payroll4Construction, and eMars rank but Miter doesn\'t. These represent an estimated 16,500 monthly searches. Given Miter\'s strong content momentum (2,514 newly ranked keywords), closing these gaps through targeted content could capture significant free traffic in the construction payroll niche.',
        type: 'info',
      },
    ],
    trafficSplit: { paid: 23, organic: 77 },
    adCopy: [
      {
        keyword: 'certified payroll',
        headline: 'Certified Payroll for Contractors - Automated Compliance',
        description: 'Simplify certified payroll reporting. Auto-generate WH-347 forms, track prevailing wages, and stay compliant. Built for construction contractors.',
      },
      {
        keyword: 'construction project management software',
        headline: 'Construction Payroll & Field Ops - Miter',
        description: 'Payroll, time tracking, HR, and expenses in one platform. Designed for contractors. Prevailing wage compliance built in. Get a demo today.',
      },
    ],
    organic: {
      keywords: 3518,
      monthlyClicks: 2638,
      estClickValue: 46400,
      page1Keywords: 595,
      fallingOffPage1: 11,
      topKeywords: [
        { keyword: 'miter', clicks: '1.3K', type: 'commercial' },
        { keyword: 'mitter', clicks: '60', type: 'commercial' },
        { keyword: 'das140', clicks: '48', type: 'informational' },
        { keyword: 'what is my fringe project rate', clicks: '36', type: 'informational' },
        { keyword: 'miter company', clicks: '36', type: 'commercial' },
        { keyword: 'construction job costing', clicks: '28', type: 'commercial' },
        { keyword: 'best payroll software for construction company', clicks: '12', type: 'commercial' },
        { keyword: 'fringe benefits calculator', clicks: '16', type: 'informational' },
      ],
      competitors: [
        { domain: 'emarsinc.com', keywords: '1.76K' },
        { domain: 'ebacon.com', keywords: '2.13K' },
        { domain: 'payroll4construction.com', keywords: '2.37K' },
        { domain: 'dapt.tech', keywords: '616' },
      ],
    },
  },
  regieai: {
    company: 'Regie.ai',
    slug: 'regieai',
    domain: 'regie.ai',
    industry: 'Sales Tech / AI Sales Engagement',
    description: 'AI-powered sales engagement platform that automates prospecting, cold calling, and pipeline generation for sales teams.',
    generatedDate: 'May 2026',
    paidKeywords: 469,
    monthlyClicks: 531,
    monthlyBudgetLow: 2500,
    monthlyBudgetHigh: 5000,
    effectiveCPC: 5.50,
    industryAvgCPC: 9.00,
    industryAvgCTR: 3.5,
    industryAvgCVR: 3.0,
    industryAvgCPL: 180,
    industryAvgWaste: 33,
    topKeywords: [
      { keyword: 'email newsletter', volume: '135K', cpc: 13.36, clickShare: 22.0, intent: 'low' },
      { keyword: 'ai', volume: '1.2M', cpc: 3.09, clickShare: 8.0, intent: 'low' },
      { keyword: 'sales agent', volume: '6.6K', cpc: 2.97, clickShare: 10.0, intent: 'medium' },
      { keyword: 'outreach.io', volume: '4.4K', cpc: 4.45, clickShare: 5.0, intent: 'medium' },
      { keyword: 'regie', volume: '930', cpc: 0.59, clickShare: 2.0, intent: 'high' },
      { keyword: 'ai sales assistant', volume: '1.3K', cpc: 6.80, clickShare: 4.0, intent: 'high' },
    ],
    competitors: [
      { domain: 'artisan.co', keywords: '4.24K', monthlyClicks: '7.55K', budget: '$46.1K', commonKeywords: 47, overlapPercent: 10 },
      { domain: 'outreach.io', keywords: '8.5K', monthlyClicks: '22K', budget: '$250K', commonKeywords: 45, overlapPercent: 10 },
      { domain: '11x.ai', keywords: '1.39K', monthlyClicks: '1.08K', budget: '$22.4K', commonKeywords: 26, overlapPercent: 6 },
      { domain: 'unifygtm.com', keywords: '3.6K', monthlyClicks: '3.8K', budget: '$0', commonKeywords: 39, overlapPercent: 8 },
    ],
    insights: [
      {
        title: 'Top paid keyword is "email newsletter" at $13.36/click',
        metric: 'Est. $17.3K/mo on a term with zero sales AI intent',
        body: 'SpyFu shows "email newsletter" as the highest-spend paid keyword at an estimated $13.36 per click and $17.3K/month. People searching this are looking for Mailchimp, Substack, or newsletter templates, not AI sales engagement software. Unless CRM data shows these clicks converting to pipeline at an unusually high rate, this looks like a significant intent mismatch consuming the bulk of paid budget.',
        type: 'danger',
      },
      {
        title: 'Bidding on "ai" at $3.09/click',
        metric: 'The single broadest keyword possible',
        body: '"AI" is one of the most generic search terms in existence, with over 1.2 million monthly searches covering everything from chatbots to image generators to homework help. For a sales engagement tool, the conversion rate on this term is almost certainly near zero. Even at a low $3.09 CPC, the volume means significant spend on clicks that will never become pipeline.',
        type: 'danger',
      },
      {
        title: 'Organic ranks declining across the board',
        metric: 'Sum rank change: -6,280 over 3 months',
        body: 'Regie.ai\'s organic rankings are deteriorating: -6,280 sum rank change over 3 months and -4,020 in the last month alone. The branded "regie" keyword has lost ranks across 5+ tracked positions. Key commercial terms like "next best action marketing," "sales cta," and "inmail linkedin template" just fell off page 1. With 16 keywords falling off page 1 vs 88 making it, the trend is negative.',
        type: 'warning',
      },
      {
        title: '469 paid keywords vs Gong\'s 31,900',
        metric: '68x keyword gap with the category leader',
        body: 'Gong.io covers 31,900 paid keywords in the sales tech space. Artisan.co covers 4,240. Regie.ai covers 469. Instead of competing on high-intent sales tool keywords where competitors dominate, the budget appears concentrated on broad, low-intent terms. CRM data would reveal whether the current keyword mix actually drives pipeline or whether reallocating toward more specific sales AI terms would perform better.',
        type: 'warning',
      },
      {
        title: '205 keywords flagged as potential ad waste',
        metric: 'Est. 51,600 monthly clicks on low-relevance terms',
        body: 'SpyFu\'s Kombat analysis flags 205 of Regie.ai\'s paid keywords as potential waste, representing an estimated 51,600 monthly clicks. Given the broad-match strategy visible in the keyword data ("ai," "email newsletter"), many of these flagged terms likely have minimal relevance to sales AI buyers. The real test is CRM conversion data.',
        type: 'info',
      },
    ],
    trafficSplit: { paid: 51, organic: 49 },
    adCopy: [
      {
        keyword: 'sales agent',
        headline: 'AI Sales Agents That Book Meetings - Regie.ai',
        description: 'Automate prospecting with AI agents that research, write, and send personalized outreach at scale. Built for revenue teams. Integrates with your SEP.',
      },
      {
        keyword: 'email newsletter',
        headline: 'AI-Powered Email Outreach - Generate More Pipeline',
        description: 'Stop writing cold emails manually. Regie.ai uses AI to generate personalized sequences that get replies. Trusted by enterprise sales teams worldwide.',
      },
    ],
    organic: {
      keywords: 872,
      monthlyClicks: 515,
      estClickValue: 9570,
      page1Keywords: 148,
      fallingOffPage1: 16,
      topKeywords: [
        { keyword: 'regie', clicks: '155', type: 'commercial' },
        { keyword: 'enterprise accounts', clicks: '24', type: 'commercial' },
        { keyword: 'next best action', clicks: '12', type: 'informational' },
        { keyword: 'cold calling techniques', clicks: '6', type: 'informational' },
        { keyword: 'email deliverability best practices', clicks: '2', type: 'informational' },
        { keyword: 'ai sales assistant', clicks: '4', type: 'commercial' },
        { keyword: 'cold calling 101', clicks: '8', type: 'informational' },
        { keyword: 'b2b sales leads', clicks: '5', type: 'commercial' },
      ],
      competitors: [
        { domain: 'roryvaden.com', keywords: '1.31K' },
        { domain: 'nonprofitcampaignlab.com', keywords: '50' },
        { domain: 'intouch365.nl', keywords: '28' },
        { domain: 'oxfordandem.com', keywords: '20' },
      ],
    },
  },
  paubox: {
    company: 'Paubox',
    slug: 'paubox',
    domain: 'paubox.com',
    industry: 'Healthcare IT / HIPAA-Compliant Email',
    description: 'HIPAA-compliant email encryption platform that lets healthcare organizations send secure emails directly from their existing provider.',
    generatedDate: 'May 2026',
    paidKeywords: 923,
    monthlyClicks: 8655,
    monthlyBudgetLow: 85000,
    monthlyBudgetHigh: 90920,
    effectiveCPC: 10.50,
    industryAvgCPC: 12.00,
    industryAvgCTR: 3.0,
    industryAvgCVR: 2.5,
    industryAvgCPL: 250,
    industryAvgWaste: 35,
    topKeywords: [
      { keyword: 'smtp', volume: '43.3K', cpc: 6.19, clickShare: 15.0, intent: 'low' },
      { keyword: 'free email', volume: '35.4K', cpc: 0.78, clickShare: 12.0, intent: 'low' },
      { keyword: 'aws', volume: '407', cpc: 1.83, clickShare: 13.0, intent: 'low' },
      { keyword: 'zoho mail', volume: '69.8K', cpc: 9.44, clickShare: 2.0, intent: 'low' },
      { keyword: 'psychiatrist vs psychologist', volume: '19.9K', cpc: 1.02, clickShare: 2.0, intent: 'low' },
      { keyword: 'hipaa compliant email', volume: '1.2K', cpc: 15.80, clickShare: 4.0, intent: 'high' },
    ],
    competitors: [
      { domain: 'hushmail.com', keywords: '313', monthlyClicks: '1.15K', budget: '$17.6K', commonKeywords: 28, overlapPercent: 3 },
      { domain: 'neocertified.com', keywords: '73', monthlyClicks: '158', budget: '$11.8K', commonKeywords: 13, overlapPercent: 1 },
      { domain: 'mailhippo.com', keywords: '191', monthlyClicks: '144', budget: '$0', commonKeywords: 15, overlapPercent: 2 },
    ],
    insights: [
      {
        title: '90% of paid keywords flagged as potential waste',
        metric: '831 of 923 keywords',
        body: 'SpyFu\'s Kombat analysis flags 831 of Paubox\'s 923 paid keywords as potential ad waste, representing an estimated 51,000 monthly clicks. At a $90.9K/month budget, the vast majority of spend appears directed at keywords with no connection to HIPAA-compliant email. The flag rate of 90% is dramatically above the 35% healthcare IT industry benchmark and suggests the paid strategy may be optimizing for volume over relevance.',
        type: 'danger',
      },
      {
        title: '$13.2K/mo on "smtp" and $9.7K/mo on "free email"',
        metric: 'Two top-spend keywords with near-zero product intent',
        body: '"SMTP" searchers want to configure mail servers or troubleshoot delivery issues. "Free email" searchers want a Gmail or Yahoo alternative. Neither audience is looking for enterprise HIPAA email encryption. Together these two keywords consume an estimated $22.9K/month, roughly 25% of the entire PPC budget, on clicks that almost certainly don\'t convert to enterprise healthcare deals.',
        type: 'danger',
      },
      {
        title: '"Psychiatrist vs psychologist" appears in the paid keyword portfolio',
        metric: '$1.02 CPC on a healthcare content term',
        body: 'SpyFu shows Paubox bidding on "psychiatrist vs psychologist," a term with 19,900 monthly searches and zero relation to email encryption. This suggests either an extremely broad match strategy pulling in unrelated queries, or a deliberate content play that\'s capturing clicks far outside the product\'s value proposition. CRM data would reveal if any of this traffic ever reaches a sales conversation.',
        type: 'warning',
      },
      {
        title: 'Organic content machine: 46.6K keywords but top traffic is off-topic',
        metric: '"what is a url" and "asymptomatic" drive more SEO clicks than "hipaa"',
        body: 'Paubox ranks for 46,647 organic keywords generating 37,700 monthly clicks worth an estimated $729K. But the highest-traffic organic terms are "what is a url" (930 clicks), "asymptomatic" (720 clicks), and "https" (480 clicks). The core product keyword "hipaa" only ranks 24th. This massive content library drives volume but the conversion path from "what is a url" to "buy HIPAA email encryption" is long.',
        type: 'warning',
      },
      {
        title: '$90.9K/mo budget dwarfs all paid competitors combined',
        metric: '5x the next largest spender (Hushmail at $17.6K)',
        body: 'Paubox\'s PPC budget is roughly 5x Hushmail and 8x Neocertified. But keyword overlap with competitors is extremely low (1-3%), meaning Paubox is mostly bidding on keywords no HIPAA email competitor targets. This could be a visionary expansion strategy, or it could mean the budget is flowing to keywords outside the category entirely. CRM attribution data would answer which.',
        type: 'info',
      },
    ],
    trafficSplit: { paid: 19, organic: 81 },
    adCopy: [
      {
        keyword: 'hipaa compliant email',
        headline: 'HIPAA Compliant Email - Seamless Encryption for Healthcare',
        description: 'Send encrypted emails from your existing inbox. No portals, no extra steps. HITRUST CSF certified. Trusted by 5,000+ healthcare organizations.',
      },
      {
        keyword: 'smtp',
        headline: 'Secure Email API & SMTP - Paubox',
        description: 'HIPAA-compliant email API and SMTP relay. Encrypt every message automatically. Zero-step encryption means recipients read emails normally.',
      },
    ],
    organic: {
      keywords: 46647,
      monthlyClicks: 37666,
      estClickValue: 729000,
      page1Keywords: 6254,
      fallingOffPage1: 1144,
      topKeywords: [
        { keyword: 'hipaa', clicks: '1.4K', type: 'informational' },
        { keyword: 'what is a url', clicks: '930', type: 'informational' },
        { keyword: 'asymptomatic', clicks: '720', type: 'informational' },
        { keyword: 'https', clicks: '480', type: 'informational' },
        { keyword: 'url meaning', clicks: '440', type: 'informational' },
        { keyword: 'hipaa compliant email', clicks: '150', type: 'commercial' },
        { keyword: 'spoofing', clicks: '300', type: 'informational' },
        { keyword: 'anonymized', clicks: '260', type: 'informational' },
      ],
      competitors: [
        { domain: 'hipaajournal.com', keywords: '69.9K' },
        { domain: 'compliancy-group.com', keywords: '33.5K' },
        { domain: 'accountablehq.com', keywords: '8.1K' },
        { domain: 'hipaaguide.net', keywords: '10.1K' },
      ],
    },
  },
  conveyor: {
    company: 'Conveyor',
    slug: 'conveyor',
    domain: 'conveyor.com',
    industry: 'Security / Trust Center & RFP Automation',
    description: 'AI-powered platform for security questionnaires, trust centers, and RFP responses that helps companies close deals faster.',
    generatedDate: 'May 2026',
    paidKeywords: 178,
    monthlyClicks: 144,
    monthlyBudgetLow: 4000,
    monthlyBudgetHigh: 4000,
    effectiveCPC: 27.70,
    industryAvgCPC: 9.00,
    industryAvgCTR: 3.5,
    industryAvgCVR: 3.0,
    industryAvgCPL: 200,
    industryAvgWaste: 30,
    topKeywords: [
      { keyword: 'conveyor', volume: '3.5K', cpc: 4.06, clickShare: 22.6, intent: 'low' },
      { keyword: 'rfp software', volume: '540', cpc: 9.07, clickShare: 32.5, intent: 'high' },
      { keyword: 'conveyer', volume: '2K', cpc: 7.81, clickShare: 7.9, intent: 'low' },
      { keyword: 'rfp response', volume: '1.1K', cpc: 2.16, clickShare: 1.6, intent: 'high' },
      { keyword: 'trust center', volume: '480', cpc: 0.45, clickShare: 0.3, intent: 'high' },
      { keyword: 'security questionnaire', volume: '720', cpc: 5.50, clickShare: 3.0, intent: 'high' },
    ],
    competitors: [
      { domain: 'responsive.io', keywords: '1.22K', monthlyClicks: '588', budget: '$17.3K', commonKeywords: 26, overlapPercent: 15 },
      { domain: '1up.ai', keywords: '275', monthlyClicks: '151', budget: '$5.03K', commonKeywords: 14, overlapPercent: 8 },
      { domain: 'tribble.ai', keywords: '257', monthlyClicks: '512', budget: '$4.11K', commonKeywords: 13, overlapPercent: 7 },
      { domain: 'sparrowgenie.com', keywords: '270', monthlyClicks: '209', budget: '$3.98K', commonKeywords: 17, overlapPercent: 10 },
    ],
    insights: [
      {
        title: 'Brand name "conveyor" is an industrial term with massive intent dilution',
        metric: '65% of organic clicks come from a generic keyword',
        body: '"Conveyor" generates 570 of Conveyor\'s 881 monthly organic clicks. But "conveyor" is overwhelmingly searched by people looking for conveyor belts, conveyor systems, and industrial equipment. The same problem hits paid: "conveyor" captures 22.6% of paid clicks at $4.06 CPC, but the vast majority of those searchers have zero interest in security questionnaire software. CRM data would reveal what percentage of "conveyor" clicks ever reach a sales conversation.',
        type: 'danger',
      },
      {
        title: 'Effective CPC is ~3x the industry average',
        metric: '$27.70 vs $9.00 benchmark',
        body: 'At $3,989/month for 144 clicks, Conveyor\'s effective CPC is approximately $27.70, roughly 3x the security SaaS benchmark. This is likely inflated by brand name competition with industrial conveyor companies who bid aggressively on "conveyor" keywords. Shifting more budget toward category terms like "rfp software" ($9.07 CPC) and "security questionnaire" could bring the effective CPC closer to industry norms while improving intent match.',
        type: 'danger',
      },
      {
        title: 'Core AI/RFP keywords falling off page 1',
        metric: '"ai rfp response" and "generative ai for rfp responses" both lost rankings',
        body: 'Two high-intent keywords, "ai rfp response" and "generative ai for rfp responses," just fell off the first page of organic results. These are exactly the terms an active buyer would search. Meanwhile, "trust center" sits at rank 15, just off page 1. With 74 keywords in "almost there" position (ranks 11-18), there\'s meaningful commercial traffic sitting just out of reach.',
        type: 'warning',
      },
      {
        title: 'Responsive.io outspends Conveyor 4x on paid search',
        metric: '$17.3K/mo vs $3.99K/mo',
        body: 'Responsive.io runs 1,220 paid keywords with a $17.3K monthly budget, capturing 588 clicks. Conveyor runs 178 keywords at $3.99K for 144 clicks. With 26 shared keywords between them, Responsive.io is likely winning most head-to-head auctions on terms like "rfp software" and "rfp response." The 4x budget gap means Conveyor is invisible on many category searches where buyers are actively comparing vendors.',
        type: 'warning',
      },
      {
        title: '"rfp software" gets the most paid clicks but at $9.07 CPC',
        metric: '32.5% of paid clicks on the highest-intent keyword',
        body: '"RFP software" is the strongest commercial keyword in Conveyor\'s paid portfolio: high intent, 540 monthly searches, and it captures 32.5% of paid clicks. At $9.07 CPC, it\'s actually in line with industry benchmarks. The question CRM data answers: what\'s the close rate on "rfp software" clicks vs. branded "conveyor" clicks? If rfp software converts meaningfully better, reallocating budget from brand defense to category terms could improve ROI.',
        type: 'info',
      },
    ],
    trafficSplit: { paid: 14, organic: 86 },
    adCopy: [
      {
        keyword: 'rfp software',
        headline: 'AI-Powered RFP Response Software - Conveyor',
        description: 'Automate security questionnaires and RFP responses with AI. Reduce response time by 80%. Trusted by security teams at fast-growing companies.',
      },
      {
        keyword: 'trust center',
        headline: 'Trust Center for Security Reviews - Conveyor',
        description: 'Share your security posture proactively. Build a trust center that answers buyer questions before they ask. Speed up security reviews and close deals faster.',
      },
    ],
    organic: {
      keywords: 695,
      monthlyClicks: 881,
      estClickValue: 4520,
      page1Keywords: 116,
      fallingOffPage1: 11,
      topKeywords: [
        { keyword: 'conveyor', clicks: '570', type: 'commercial' },
        { keyword: 'external source', clicks: '20', type: 'informational' },
        { keyword: 'convayer', clicks: '18', type: 'commercial' },
        { keyword: 'security questionnaire software', clicks: '4', type: 'commercial' },
        { keyword: 'trust center', clicks: '6', type: 'commercial' },
        { keyword: 'conveyor media', clicks: '5', type: 'informational' },
        { keyword: 'trust on the internet', clicks: '8', type: 'informational' },
        { keyword: 'conveyor company', clicks: '3', type: 'commercial' },
      ],
      competitors: [
        { domain: 'deeprfp.com', keywords: '416' },
        { domain: 'sequesto.com', keywords: '243' },
        { domain: 'powerrfp.com', keywords: '87' },
        { domain: 'pinprodesigns.com', keywords: '7' },
      ],
    },
  },
  leadiq: {
    company: 'LeadIQ',
    slug: 'leadiq',
    domain: 'leadiq.com',
    industry: 'Sales Intelligence / B2B Prospecting',
    description: 'B2B prospecting platform that helps sales teams find, capture, and sync verified contact data to their CRM.',
    generatedDate: 'May 2026',
    paidKeywords: 265,
    monthlyClicks: 2972,
    monthlyBudgetLow: 3000,
    monthlyBudgetHigh: 5000,
    effectiveCPC: 1.12,
    industryAvgCPC: 8.50,
    industryAvgCTR: 3.0,
    industryAvgCVR: 2.8,
    industryAvgCPL: 350,
    industryAvgWaste: 32,
    topKeywords: [
      { keyword: 'zoominfo', volume: '53K', cpc: 4.88, clickShare: 29.8, intent: 'low' },
      { keyword: 'zoom info', volume: '16K', cpc: 5.45, clickShare: 32.4, intent: 'low' },
      { keyword: 'lusha', volume: '8.1K', cpc: 0.45, clickShare: 28.3, intent: 'low' },
      { keyword: 'leadiq', volume: '4K', cpc: 0.00, clickShare: 17.1, intent: 'high' },
      { keyword: 'seamless ai', volume: '9.3K', cpc: 0.00, clickShare: 8.77, intent: 'low' },
    ],
    competitors: [
      { domain: 'apollo.io', keywords: '19.4K', monthlyClicks: '21.3K', budget: '$101K', commonKeywords: 99, overlapPercent: 37 },
      { domain: 'salesintel.io', keywords: '821', monthlyClicks: '5.32K', budget: '$15.6K', commonKeywords: 54, overlapPercent: 20 },
      { domain: 'kernel.ai', keywords: '891', monthlyClicks: '5.84K', budget: '$89.7K', commonKeywords: 11, overlapPercent: 4 },
      { domain: 'lead411.com', keywords: '248', monthlyClicks: '0', budget: '$1.24K', commonKeywords: 26, overlapPercent: 10 },
    ],
    insights: [
      {
        title: '82% of paid clicks target competitor brand names',
        metric: '"zoominfo" + "zoom info" capture 62% of clicks alone',
        body: 'LeadIQ\'s top paid keywords are "zoominfo" ($4.88 CPC, 29.8% of clicks) and "zoom info" ($5.45 CPC, 32.4% of clicks). Add "lusha" and "seamless ai" and roughly 82% of paid traffic comes from people searching for a competitor by name. Competitor conquesting typically converts at 1-2% because the searcher already has a product in mind. Meanwhile, category terms like "sales intelligence software" or "B2B prospecting tool" are absent from the paid portfolio entirely.',
        type: 'danger',
      },
      {
        title: 'Apollo.io outspends LeadIQ ~30x on paid search',
        metric: '19,400 paid keywords vs 265',
        body: 'Apollo.io runs 19,400 paid keywords with an estimated $101K/mo budget. LeadIQ runs 265 keywords at ~$3.3K/mo. They share 99 common keywords. At a 30x spend gap, Apollo.io likely dominates auction visibility on every overlapping term. SalesIntel.io ($15.6K/mo, 821 keywords) and Kernel.ai ($89.7K/mo, 891 keywords) also outspend LeadIQ significantly. The current budget level means LeadIQ is essentially invisible on paid search outside branded queries.',
        type: 'danger',
      },
      {
        title: '26% of paid keywords flagged as potential ad waste',
        metric: '69 keywords generating ~2,070 clicks with low ROI signal',
        body: 'SpyFu\'s competitive analysis flags 69 of LeadIQ\'s 265 paid keywords as potential waste, generating roughly 2,070 monthly clicks. At $1.12 effective CPC, that\'s an estimated $2.3K/mo flowing to keywords where competing ads are better positioned or the search intent doesn\'t match. CRM attribution data would reveal which of these clicks actually create pipeline conversations vs. which just inflate the click count.',
        type: 'warning',
      },
      {
        title: '$1.12 effective CPC masks a split strategy',
        metric: 'Brand at $0 + competitor terms at $4-5',
        body: 'LeadIQ\'s blended CPC ($1.12) looks efficient against the $8.50 industry average. But it\'s a mix of free branded clicks on "leadiq" (17.1% of traffic) pulling down the average, while competitor conquesting on "zoominfo" ($4.88) and "zoom info" ($5.45) drives the actual spend. The real question: do those $5 competitor clicks produce pipeline, or do they just inflate the click count while searchers bounce back to ZoomInfo?',
        type: 'info',
      },
      {
        title: '7,821 keywords just fell off page 1 organically',
        metric: '79,601 more in the "almost there" zone (ranks 11-16)',
        body: 'Organic drives 99% of LeadIQ\'s traffic, generating 443K monthly clicks worth an estimated $4.86M. But 7,821 keywords just dropped off page 1. With 79,601 keywords sitting in ranks 11-16, every small ranking improvement could unlock meaningful traffic. The company directory pages (SunTrust, Fingerhut, USGS) drive the highest organic click volume, but core product terms like "sales intelligence" and "B2B prospecting" need page 1 visibility to capture commercial intent.',
        type: 'warning',
      },
    ],
    trafficSplit: { paid: 1, organic: 99 },
    adCopy: [
      {
        keyword: 'zoominfo',
        headline: 'LeadIQ - ZoomInfo Alternative',
        description: 'Get verified B2B contact data without the enterprise contract. One-click capture from LinkedIn. Syncs directly to Salesforce and HubSpot.',
      },
      {
        keyword: 'lusha',
        headline: 'B2B Contact Data Platform - LeadIQ',
        description: 'Find prospect emails and phone numbers as you browse LinkedIn. Built for sales teams that move fast. Start free today.',
      },
    ],
    organic: {
      keywords: 628910,
      monthlyClicks: 443150,
      estClickValue: 4860000,
      page1Keywords: 36943,
      fallingOffPage1: 7821,
      topKeywords: [
        { keyword: 'suntrust', clicks: '4.8K', type: 'informational' },
        { keyword: 'fingerhut', clicks: '1.6K', type: 'informational' },
        { keyword: 'usgs', clicks: '1.1K', type: 'informational' },
        { keyword: 'gun broker', clicks: '1K', type: 'informational' },
        { keyword: 'parchment', clicks: '1K', type: 'informational' },
        { keyword: 'leadiq', clicks: '450', type: 'commercial' },
        { keyword: 'georgia secretary of state', clicks: '440', type: 'informational' },
        { keyword: 'signs365', clicks: '320', type: 'informational' },
      ],
      competitors: [
        { domain: 'zoominfo.com', keywords: '3.18M' },
        { domain: 'rocketreach.co', keywords: '1.95M' },
        { domain: 'linkedin.com', keywords: '37.1M' },
        { domain: 'bloomberg.com', keywords: '3.54M' },
      ],
    },
  },
  usergems: {
    company: 'UserGems',
    slug: 'usergems',
    domain: 'usergems.com',
    industry: 'Sales Intelligence / Account-Based Marketing',
    description: 'Buyer signal platform that tracks job changes and buying intent to generate pipeline for B2B sales teams.',
    generatedDate: 'May 2026',
    paidKeywords: 211,
    monthlyClicks: 149,
    monthlyBudgetLow: 3650,
    monthlyBudgetHigh: 3650,
    effectiveCPC: 24.50,
    industryAvgCPC: 12.50,
    industryAvgCTR: 2.8,
    industryAvgCVR: 2.5,
    industryAvgCPL: 420,
    industryAvgWaste: 35,
    topKeywords: [
      { keyword: '6sense', volume: '5.7K', cpc: 4.72, clickShare: 4.62, intent: 'low' },
      { keyword: 'account based marketing', volume: '4.8K', cpc: 18.28, clickShare: 8.47, intent: 'medium' },
      { keyword: 'common room', volume: '1.5K', cpc: 0.48, clickShare: 0, intent: 'low' },
      { keyword: 'abm marketing', volume: '1.4K', cpc: 13.83, clickShare: 0, intent: 'medium' },
      { keyword: '6 sense', volume: '1.1K', cpc: 4.19, clickShare: 3.57, intent: 'low' },
    ],
    competitors: [
      { domain: 'influ2.com', keywords: '5.01K', monthlyClicks: '11.6K', budget: '$162K', commonKeywords: 99, overlapPercent: 47 },
      { domain: 'factors.ai', keywords: '2.07K', monthlyClicks: '1.41K', budget: '$32.2K', commonKeywords: 86, overlapPercent: 41 },
      { domain: 'madisonlogic.com', keywords: '1.18K', monthlyClicks: '169', budget: '$8.77K', commonKeywords: 37, overlapPercent: 18 },
      { domain: 'getseam.ai', keywords: '47', monthlyClicks: '13', budget: '$1.56K', commonKeywords: 18, overlapPercent: 9 },
    ],
    insights: [
      {
        title: 'Competitor Brand Bidding Dominates Spend',
        metric: '60% of top keywords are competitor names',
        body: 'Three of your five highest-volume PPC keywords are competitor brands (6sense, common room, 6 sense). You\'re paying $4-5 per click for traffic that\'s searching for someone else. These clicks rarely convert because the searcher already has a vendor in mind.',
        type: 'danger',
      },
      {
        title: 'Massively Outspent by Competitors',
        metric: 'Influ2 spends 44x your PPC budget',
        body: 'Influ2 spends ~$162K/mo vs your $3.65K. Factors.ai spends $32.2K (9x more). With 211 paid keywords against Influ2\'s 5,010, you\'re fighting for visibility in a space where competitors are buying market share with volume.',
        type: 'danger',
      },
      {
        title: 'ABM Keywords Are Expensive but Category-Relevant',
        metric: '"account based marketing" costs $18.28/click',
        body: '"Account based marketing" and "abm marketing" are your only category-relevant PPC terms, costing $13-18 per click. These are worth keeping if they convert, but at this CPC you need tight conversion tracking to justify the spend.',
        type: 'warning',
      },
      {
        title: 'Organic Carries 85% of Traffic',
        metric: '$37.7K estimated organic click value',
        body: 'Your organic program generates $37.7K in estimated monthly value from 832 clicks, dwarfing your $3.65K PPC spend. Organic is doing the heavy lifting. The risk: 71 keywords just fell off page 1, including "sales tools" and "warm lead."',
        type: 'info',
      },
      {
        title: '71 Keywords Just Fell Off Page 1',
        metric: '71 keywords dropped from page 1 rankings',
        body: 'Key terms like "sales tools," "sales management blogs," "warm lead," and "hot leads" recently fell off page 1. With organic driving 85% of your traffic, these rank losses could materially impact pipeline if the trend continues.',
        type: 'warning',
      },
    ],
    trafficSplit: { paid: 15, organic: 85 },
    adCopy: [
      { headline: 'Track Buyer Job Changes | UserGems', description: 'Know when your champions switch companies. Generate 2x more pipeline with verified buyer signals.', keyword: '6sense' },
      { headline: 'Account-Based Marketing Platform | UserGems', description: 'Target accounts showing real buying signals. Track job changes, funding events, and intent data.', keyword: 'account based marketing' },
    ],
    organic: {
      keywords: 3511,
      monthlyClicks: 832,
      estClickValue: 37700,
      page1Keywords: 416,
      fallingOffPage1: 71,
      topKeywords: [
        { keyword: 'usergems', clicks: '70', type: 'commercial' },
        { keyword: 'voicemail script', clicks: '40', type: 'informational' },
        { keyword: 'sales cycle', clicks: '16', type: 'informational' },
        { keyword: 'buying triggers', clicks: '12', type: 'commercial' },
        { keyword: 'voicemail scripts for sales', clicks: '12', type: 'informational' },
        { keyword: 'tools for sales reps', clicks: '10', type: 'commercial' },
        { keyword: 'b2b prospecting methods', clicks: '7', type: 'commercial' },
        { keyword: 'marketing tools for sales reps', clicks: '9', type: 'commercial' },
      ],
      competitors: [
        { domain: 'cognism.com', keywords: '34.3K' },
        { domain: 'salesmotion.io', keywords: '6.3K' },
        { domain: 'warmly.ai', keywords: '3.92K' },
        { domain: 'only-b2b.com', keywords: '3.07K' },
      ],
    },
  },
}
