-- 001_apps_schema.sql — the "juno-apps" Supabase project (split from the Pen project, 8 Oct 2026).
-- Holds VC Constellation (vc_*) and Daily Brief (news_*). Juno Pen stays in the original project.
-- Built from supabase/migrations/007–013, lib/vc/migrations/2026-10-01-funding-events.sql and
-- lib/news/schema.sql, checked against the live columns on 8 Oct (adds news_feed_cache.brief).
-- Paste into the NEW project's SQL editor. Safe to re-run.
--
-- Differences from the original project, on purpose:
--   * news_topics.id is "generated by default" (not "always") so the copy can keep the old ids.
--   * RLS is enabled on the news_* tables too (service-role only; the code never uses the anon client for them).

create extension if not exists pgcrypto;  -- gen_random_uuid()
create extension if not exists pg_trgm;   -- fast name ILIKE search

-- ───────────────────────── VC Constellation: curated graph ─────────────────────────

create table if not exists vc_firms (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  kind text not null default 'vc',
  website text,
  created_at timestamptz not null default now()
);

create table if not exists vc_filings (
  id uuid primary key default gen_random_uuid(),
  accession text unique not null,
  form_type text not null default 'D',
  cik text,
  issuer_name text,
  filing_date date,
  offering_amount numeric,
  industry_group text,
  url text,
  processed_at timestamptz not null default now()
);

create table if not exists vc_companies (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  cik text unique,
  sector text,
  location text,
  total_raised text,
  last_round text,
  last_round_amount numeric,
  last_round_date date,
  created_at timestamptz not null default now(),
  website text,
  description text,
  founded_year int,
  headcount text,
  founders text,
  profile_source_url text,
  profile_updated_at timestamptz
);

create table if not exists vc_people (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  norm_name text not null,
  firm_id uuid references vc_firms(id),
  title text,
  bio text,
  profile_url text,
  linkedin text,
  x_url text,
  kind text not null default 'partner',
  created_at timestamptz not null default now(),
  unique (norm_name, firm_id)
);

create table if not exists vc_investments (
  id uuid primary key default gen_random_uuid(),
  firm_id uuid not null references vc_firms(id),
  company_id uuid not null references vc_companies(id),
  partner_id uuid references vc_people(id),
  round text,
  amount_text text,
  amount_num numeric,
  date text,
  lead boolean not null default false,
  confidence text default 'medium',
  source_text text,
  source_url text,
  filing_id uuid references vc_filings(id),
  created_at timestamptz not null default now(),
  unique (firm_id, company_id, round, date)
);

create table if not exists vc_board_seats (
  id uuid primary key default gen_random_uuid(),
  person_id uuid references vc_people(id),
  company_id uuid not null references vc_companies(id),
  firm_id uuid references vc_firms(id),
  person_name text not null,
  role text default 'Board Member',
  as_of date,
  confidence text default 'medium',
  source_kind text not null default 'news',
  source_text text,
  source_url text,
  filing_id uuid references vc_filings(id),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  unique (person_name, company_id, firm_id)
);

create table if not exists vc_info_requests (
  id uuid primary key default gen_random_uuid(),
  company_query text not null,
  note text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists vc_sync_log (
  id uuid primary key default gen_random_uuid(),
  run_at timestamptz not null default now(),
  source text not null,
  filings_processed int default 0,
  new_companies int default 0,
  new_people int default 0,
  new_board_seats int default 0,
  notes text
);

create index if not exists idx_vc_people_norm      on vc_people (norm_name);
create index if not exists idx_vc_people_firm      on vc_people (firm_id);
create index if not exists idx_vc_companies_cik    on vc_companies (cik);
create index if not exists idx_vc_companies_sector on vc_companies (sector);
create index if not exists idx_vc_companies_lastamt on vc_companies (last_round_amount desc nulls last);
create index if not exists idx_vc_board_company    on vc_board_seats (company_id);
create index if not exists idx_vc_board_person     on vc_board_seats (person_id);
create index if not exists idx_vc_board_firm       on vc_board_seats (firm_id);
create index if not exists idx_vc_inv_company      on vc_investments (company_id);
create index if not exists idx_vc_inv_firm         on vc_investments (firm_id);
create index if not exists idx_vc_filings_cik      on vc_filings (cik);

-- ───────────────────────── VC Constellation: Form D universe ─────────────────────────

create table if not exists vc_formd_issuers (
  cik text primary key,
  name text not null,
  norm_name text,
  industry_group text,
  state text,
  country text,
  first_filing_date date,
  last_filing_date date,
  last_offering_amount numeric,
  total_offering_amount numeric,
  filing_count int default 0,
  revenue_range text,
  updated_at timestamptz not null default now(),
  entity_type text,
  type_confidence text
);

create table if not exists vc_ingest_meta (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists vc_formd_persons (
  person_key text primary key,
  name text not null,
  filing_count int default 0,
  issuer_count int default 0,
  roles text[],
  first_seen date,
  last_seen date,
  linkedin text,
  x text,
  profile_url text,
  updated_at timestamptz not null default now()
);

create table if not exists vc_formd_person_issuers (
  person_key text not null,
  cik text not null,
  issuer_name text,
  roles text[],
  first_date date,
  last_date date,
  filing_count int default 0,
  primary key (person_key, cik)
);

create table if not exists vc_funding_overrides (
  company_slug text primary key,
  cik text,
  verified_total_raised numeric,
  last_round text,
  source_url text,
  note text,
  updated_at timestamptz not null default now()
);

create index if not exists idx_formd_name_trgm          on vc_formd_issuers using gin (name gin_trgm_ops);
create index if not exists idx_formd_industry           on vc_formd_issuers (industry_group);
create index if not exists idx_formd_state              on vc_formd_issuers (state);
create index if not exists idx_formd_lastamt            on vc_formd_issuers (last_offering_amount desc nulls last);
create index if not exists idx_formd_lastdate           on vc_formd_issuers (last_filing_date desc);
create index if not exists idx_formd_entity_type        on vc_formd_issuers (entity_type);
create index if not exists idx_formd_persons_name_trgm  on vc_formd_persons using gin (name gin_trgm_ops);
create index if not exists idx_formd_persons_filings    on vc_formd_persons (filing_count desc);
create index if not exists idx_formd_pi_cik             on vc_formd_person_issuers (cik);

-- ───────────────────────── VC Constellation: chat, queue, users ─────────────────────────

create table if not exists vc_chat_conversations (
  id uuid primary key default gen_random_uuid(),
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_email text
);

create table if not exists vc_chat_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references vc_chat_conversations(id) on delete cascade,
  role text not null,
  content jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists vc_result_sets (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references vc_chat_conversations(id) on delete cascade,
  interpretation text,
  filters jsonb,
  columns text[] not null,
  rows jsonb not null,
  total int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists vc_chat_runs (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references vc_chat_conversations(id) on delete set null,
  model text,
  turns int default 0,
  tools jsonb,
  input_tokens int default 0,
  output_tokens int default 0,
  cache_read_tokens int default 0,
  cache_write_tokens int default 0,
  cost_usd numeric,
  duration_ms int,
  status text,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_msgs_conv   on vc_chat_messages (conversation_id, created_at);
create index if not exists idx_chat_runs_day    on vc_chat_runs (created_at);
create index if not exists idx_result_sets_conv on vc_result_sets (conversation_id);

create table if not exists vc_enrich_queue (
  id uuid primary key default gen_random_uuid(),
  company_slug text not null,
  company_name text,
  kind text not null,
  payload jsonb not null,
  confidence text,
  source_url text,
  status text not null default 'pending',
  run_note text,
  created_at timestamptz not null default now(),
  decided_at timestamptz
);
create index if not exists idx_enrich_q_status on vc_enrich_queue (status, created_at);

create table if not exists vc_user_state (
  user_email text primary key,
  watchlist jsonb not null default '[]'::jsonb,
  saved_queries jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists vc_memos (
  company_slug text primary key,
  memo text,
  sources jsonb,
  model text,
  user_email text,
  updated_at timestamptz not null default now()
);

create table if not exists vc_funding_events (
  id              uuid primary key default gen_random_uuid(),
  company_slug    text,
  cik             text,
  company_name    text not null,
  round           text,
  amount_usd      numeric,
  valuation_usd   numeric,
  investors       jsonb not null default '[]'::jsonb,
  announced_on    date,
  source_url      text not null,
  source_name     text,
  source_tier     int,
  headline        text,
  other_sources   jsonb not null default '[]'::jsonb,
  confidence      numeric,
  status          text not null default 'reported' check (status in ('reported', 'hidden')),
  dedupe_key      text unique not null,
  created_company boolean not null default false,
  created_at      timestamptz not null default now()
);
create index if not exists vc_funding_events_company_idx   on vc_funding_events (company_slug, announced_on desc);
create index if not exists vc_funding_events_announced_idx on vc_funding_events (announced_on desc);
create index if not exists vc_funding_events_status_idx    on vc_funding_events (status);

-- ───────────────────────── Daily Brief (news) ─────────────────────────

create table if not exists news_topics (
  id          bigint generated by default as identity primary key,
  user_email  text not null,
  query       text not null,
  route       jsonb default '{}'::jsonb,
  brief       text,
  items       jsonb default '[]'::jsonb,
  created_at  timestamptz default now(),
  unique (user_email, query)
);
create index if not exists news_topics_user on news_topics(user_email);

create table if not exists news_prefs (
  user_email  text primary key,
  lang        text default 'en',
  layout      jsonb default '{}'::jsonb,
  updated_at  timestamptz default now()
);

create table if not exists news_profile (
  user_email  text primary key,
  profile     jsonb default '{}'::jsonb,
  updated_at  timestamptz default now()
);

create table if not exists news_feed_cache (
  section     text primary key,
  items       jsonb default '[]'::jsonb,
  brief       text,
  updated_at  timestamptz default now()
);

create table if not exists news_macro_cache (
  id          int primary key default 1,
  stats       jsonb default '[]'::jsonb,
  updated_at  timestamptz default now()
);

create table if not exists news_translations (
  link        text primary key,
  es          text,
  updated_at  timestamptz default now()
);

-- ───────────────────────── Row-level security ─────────────────────────
-- Same as the original project: graph + Form D tables are public-read, info_requests takes anon inserts,
-- everything else is service-role only (RLS on, no policies).

alter table vc_firms                enable row level security;
alter table vc_people               enable row level security;
alter table vc_companies            enable row level security;
alter table vc_investments          enable row level security;
alter table vc_board_seats          enable row level security;
alter table vc_filings              enable row level security;
alter table vc_info_requests        enable row level security;
alter table vc_sync_log             enable row level security;
alter table vc_formd_issuers        enable row level security;
alter table vc_ingest_meta          enable row level security;
alter table vc_formd_persons        enable row level security;
alter table vc_formd_person_issuers enable row level security;
alter table vc_funding_overrides    enable row level security;
alter table vc_chat_conversations   enable row level security;
alter table vc_chat_messages        enable row level security;
alter table vc_result_sets          enable row level security;
alter table vc_chat_runs            enable row level security;
alter table vc_enrich_queue         enable row level security;
alter table vc_user_state           enable row level security;
alter table vc_memos                enable row level security;
alter table vc_funding_events       enable row level security;
alter table news_topics             enable row level security;
alter table news_prefs              enable row level security;
alter table news_profile            enable row level security;
alter table news_feed_cache         enable row level security;
alter table news_macro_cache        enable row level security;
alter table news_translations       enable row level security;

drop policy if exists "public read vc_firms"                on vc_firms;
drop policy if exists "public read vc_people"               on vc_people;
drop policy if exists "public read vc_companies"            on vc_companies;
drop policy if exists "public read vc_investments"          on vc_investments;
drop policy if exists "public read vc_board_seats"          on vc_board_seats;
drop policy if exists "public read vc_filings"              on vc_filings;
drop policy if exists "anon insert vc_info_requests"        on vc_info_requests;
drop policy if exists "public read vc_formd_issuers"        on vc_formd_issuers;
drop policy if exists "public read vc_ingest_meta"          on vc_ingest_meta;
drop policy if exists "public read vc_formd_persons"        on vc_formd_persons;
drop policy if exists "public read vc_formd_person_issuers" on vc_formd_person_issuers;
drop policy if exists "public read vc_funding_overrides"    on vc_funding_overrides;
drop policy if exists "public read vc_funding_events"       on vc_funding_events;

create policy "public read vc_firms"                on vc_firms                for select using (true);
create policy "public read vc_people"               on vc_people               for select using (true);
create policy "public read vc_companies"            on vc_companies            for select using (true);
create policy "public read vc_investments"          on vc_investments          for select using (true);
create policy "public read vc_board_seats"          on vc_board_seats          for select using (true);
create policy "public read vc_filings"              on vc_filings              for select using (true);
create policy "anon insert vc_info_requests"        on vc_info_requests        for insert with check (true);
create policy "public read vc_formd_issuers"        on vc_formd_issuers        for select using (true);
create policy "public read vc_ingest_meta"          on vc_ingest_meta          for select using (true);
create policy "public read vc_formd_persons"        on vc_formd_persons        for select using (true);
create policy "public read vc_formd_person_issuers" on vc_formd_person_issuers for select using (true);
create policy "public read vc_funding_overrides"    on vc_funding_overrides    for select using (true);
create policy "public read vc_funding_events"       on vc_funding_events       for select using (status = 'reported');

notify pgrst, 'reload schema';
