/** The retrieval index, imported as a build artifact (see research/adr-001-retrieval.md).
 *  Generated by scripts/build-index.mjs — never edit lib/search-index.json by hand.
 *  This module exists so the JSON import happens in exactly one place and
 *  lib/retrieval.ts stays a pure, testable function of an index. */
import rawIndex from "./search-index.json";

export type ChunkKind = "page" | "fact";

export interface Chunk {
  id: string;
  kind: ChunkKind;
  /** Route the chunk is readable at, e.g. "/stack/cloud" or "/sources". */
  page: string;
  heading: string;
  /** Element id on that page — deep-linked as `${page}#${anchor}`. "" = page top. */
  anchor: string;
  layer: string;
  /** Fact ids cited within this span. Never contains a quarantined id. */
  factIds: string[];
  text: string;
}

export interface PageMeta {
  title: string;
  kind: string;
  layer: string;
  anchors: string[];
}

export interface Bm25Stats {
  k1: number;
  b: number;
  /** Document count. */
  N: number;
  avgdl: number;
  docLens: number[];
  idf: Record<string, number>;
  /** term → [chunkIndex, termFrequency][] */
  postings: Record<string, [number, number][]>;
}

export interface SearchIndex {
  version: number;
  tokenizer: { version: number; probe: string; probeTokens: string[] };
  bm25: Bm25Stats;
  pages: Record<string, PageMeta>;
  /** Every citable (non-quarantined) fact id. */
  factIds: string[];
  chunks: Chunk[];
}

/** The JSON's inferred structural type is far wider than SearchIndex (every
 *  string is `string`, every union collapses), so this is a deliberate cast to
 *  the contract scripts/build-index.mjs writes. */
export const SEARCH_INDEX = rawIndex as unknown as SearchIndex;
